from typing import List

alice_in_wonderland: List[List[str]] = [
    ['alices', 'adventures', 'in', 'wonderland'],
    ['down', 'the', 'rabbithole'],
    ['alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'of',
     'sitting', 'by', 'her', 'sister', 'on', 'the', 'bank', 'and', 'of',
     'having', 'nothing', 'to', 'do', 'once', 'or', 'twice', 'she', 'had',
     'peeped', 'into', 'the', 'book', 'her', 'sister', 'was', 'reading',
     'but', 'it', 'had', 'no', 'pictures', 'or', 'conversations', 'in',
     'it', 'and', 'what', 'is', 'the', 'use', 'of', 'a', 'book', 'thought',
     'alice', 'without', 'pictures', 'or', 'conversations'],
    ['so', 'she', 'was', 'considering', 'in', 'her', 'own', 'mind', '(as',
     'well', 'as', 'she', 'could', 'for', 'the', 'day', 'made', 'her',
     'feel', 'very', 'sleepy', 'and', 'stupid)', 'whether', 'the',
     'pleasure', 'of', 'making', 'a', 'daisychain', 'would', 'be', 'worth',
     'the', 'trouble', 'of', 'getting', 'up', 'and', 'picking', 'the',
     'daisies', 'when', 'suddenly', 'a', 'white', 'rabbit', 'with', 'pink',
     'eyes', 'ran', 'close', 'by', 'her'],
    ['there', 'was', 'nothing', 'so', 'very', 'remarkable', 'in', 'that',
     'nor', 'did', 'alice', 'think', 'it', 'so', 'very', 'much', 'out',
     'of', 'the', 'way', 'to', 'hear', 'the', 'rabbit', 'say', 'to',
     'itself', 'oh', 'dear'],
    ['oh', 'dear'],
    ['i', 'shall', 'be', 'too', 'late'],
    ['but', 'when', 'the', 'rabbit', 'actually', 'took', 'a', 'watch',
     'out', 'of', 'its', 'waistcoatpocket', 'and', 'looked', 'at', 'it',
     'and', 'then', 'hurried', 'on', 'alice', 'started', 'to', 'her',
     'feet', 'for', 'it', 'flashed', 'across', 'her', 'mind', 'that', 'she',
     'had', 'never', 'before', 'seen', 'a', 'rabbit', 'with', 'either', 'a',
     'waistcoatpocket', 'or', 'a', 'watch', 'to', 'take', 'out', 'of', 'it',
     'and', 'burning', 'with', 'curiosity', 'she', 'ran', 'across', 'the',
     'field', 'after', 'it', 'and', 'was', 'just', 'in', 'time', 'to',
     'see', 'it', 'pop', 'down', 'a', 'large', 'rabbithole', 'under', 'the',
     'hedge'],
    ['in', 'another', 'moment', 'down', 'went', 'alice', 'after', 'it'],
    ['the', 'rabbithole', 'went', 'straight', 'on', 'like', 'a', 'tunnel',
     'for', 'some', 'way', 'and', 'then', 'dipped', 'suddenly', 'down',
     'so', 'suddenly', 'that', 'alice', 'had', 'not', 'a', 'moment', 'to',
     'think', 'about', 'stopping', 'herself', 'before', 'she', 'found',
     'herself', 'falling', 'down', 'what', 'seemed', 'to', 'be', 'a',
     'very', 'deep', 'well'],
    ['either', 'the', 'well', 'was', 'very', 'deep', 'or', 'she', 'fell',
     'very', 'slowly', 'for', 'she', 'had', 'plenty', 'of', 'time', 'as',
     'she', 'went', 'down', 'to', 'look', 'about', 'her'],
    ['first', 'she', 'tried', 'to', 'make', 'out', 'what', 'she', 'was',
     'coming', 'to', 'but', 'it', 'was', 'too', 'dark', 'to', 'see',
     'anything;', 'then', 'she', 'looked', 'at', 'the', 'sides', 'of',
     'the', 'well', 'and', 'noticed', 'that', 'they', 'were', 'filled',
     'with', 'cupboards', 'and', 'bookshelves;', 'here', 'and', 'there',
     'she', 'saw', 'maps', 'and', 'pictures', 'hung', 'upon', 'pegs'],
    ['she', 'took', 'down', 'a', 'jar', 'from', 'one', 'of', 'the',
     'shelves', 'as', 'she', 'passed'],
    ['it', 'was', 'labeled', 'orange', 'marmalade', 'but', 'to', 'her',
     'great', 'disappointment', 'it', 'was', 'empty;', 'she', 'did', 'not',
     'like', 'to', 'drop', 'the', 'jar', 'so', 'managed', 'to', 'put', 'it',
     'into', 'one', 'of', 'the', 'cupboards', 'as', 'she', 'fell', 'past',
     'it'],
    ['down', 'down', 'down'],
    ['would', 'the', 'fall', 'never', 'come', 'to', 'an', 'end'],
    ['there', 'was', 'nothing', 'else', 'to', 'do', 'so', 'alice', 'soon',
     'began', 'talking', 'to', 'herself'],
    ['dinahll', 'miss', 'me', 'very', 'much', 'tonight', 'i', 'should',
     'think', '(dinah', 'was', 'the', 'cat)', 'i', 'hope', 'theyll',
     'remember', 'her', 'saucer', 'of', 'milk', 'at', 'teatime'],
    ['dinah', 'my', 'dear', 'i', 'wish', 'you', 'were', 'down', 'here',
     'with', 'me'],
    ['alice', 'felt', 'that', 'she', 'was', 'dozing', 'off', 'when',
     'suddenly', 'thump'],
    ['thump'],
    ['down', 'she', 'came', 'upon', 'a', 'heap', 'of', 'sticks', 'and',
     'dry', 'leaves', 'and', 'the', 'fall', 'was', 'over'],
    ['alice', 'was', 'not', 'a', 'bit', 'hurt', 'and', 'she', 'jumped',
     'up', 'in', 'a', 'moment'],
    ['she', 'looked', 'up', 'but', 'it', 'was', 'all', 'dark', 'overhead;',
     'before', 'her', 'was', 'another', 'long', 'passage', 'and', 'the',
     'white', 'rabbit', 'was', 'still', 'in', 'sight', 'hurrying', 'down',
     'it'],
    ['there', 'was', 'not', 'a', 'moment', 'to', 'be', 'lost'],
    ['away', 'went', 'alice', 'like', 'the', 'wind', 'and', 'was', 'just',
     'in', 'time', 'to', 'hear', 'it', 'say', 'as', 'it', 'turned', 'a',
     'corner', 'oh', 'my', 'ears', 'and', 'whiskers', 'how', 'late', 'its',
     'getting'],
    ['she', 'was', 'close', 'behind', 'it', 'when', 'she', 'turned', 'the',
     'corner', 'but', 'the', 'rabbit', 'was', 'no', 'longer', 'to', 'be',
     'seen'],
    ['she', 'found', 'herself', 'in', 'a', 'long', 'low', 'hall', 'which',
     'was', 'lit', 'up', 'by', 'a', 'row', 'of', 'lamps', 'hanging', 'from',
     'the', 'roof'],
    ['there', 'were', 'doors', 'all', 'round', 'the', 'hall', 'but', 'they',
     'were', 'all', 'locked;', 'and', 'when', 'alice', 'had', 'been', 'all',
     'the', 'way', 'down', 'one', 'side', 'and', 'up', 'the', 'other',
     'trying', 'every', 'door', 'she', 'walked', 'sadly', 'down', 'the',
     'middle', 'wondering', 'how', 'she', 'was', 'ever', 'to', 'get', 'out',
     'again'],
    ['suddenly', 'she', 'came', 'upon', 'a', 'little', 'table', 'all',
     'made', 'of', 'solid', 'glass'],
    ['there', 'was', 'nothing', 'on', 'it', 'but', 'a', 'tiny', 'golden',
     'key', 'and', 'alices', 'first', 'idea', 'was', 'that', 'this',
     'might', 'belong', 'to', 'one', 'of', 'the', 'doors', 'of', 'the',
     'hall;', 'but', 'alas'],
    ['either', 'the', 'locks', 'were', 'too', 'large', 'or', 'the', 'key',
     'was', 'too', 'small', 'but', 'at', 'any', 'rate', 'it', 'would',
     'not', 'open', 'any', 'of', 'them'],
    ['however', 'on', 'the', 'second', 'time', 'round', 'she', 'came',
     'upon', 'a', 'low', 'curtain', 'she', 'had', 'not', 'noticed',
     'before', 'and', 'behind', 'it', 'was', 'a', 'little', 'door', 'about',
     'fifteen', 'inches', 'high'],
    ['she', 'tried', 'the', 'little', 'golden', 'key', 'in', 'the', 'lock',
     'and', 'to', 'her', 'great', 'delight', 'it', 'fitted'],
    ['', 'alice', 'opened', 'the', 'door', 'and', 'found', 'that', 'it',
     'led', 'into', 'a', 'small', 'passage', 'not', 'much', 'larger',
     'than', 'a', 'rathole;', 'she', 'knelt', 'down', 'and', 'looked',
     'along', 'the', 'passage', 'into', 'the', 'loveliest', 'garden', 'you',
     'ever', 'saw'],
    ['how', 'she', 'longed', 'to', 'get', 'out', 'of', 'that', 'dark',
     'hall', 'and', 'wander', 'about', 'among', 'those', 'beds', 'of',
     'bright', 'flowers', 'and', 'those', 'cool', 'fountains', 'but', 'she',
     'could', 'not', 'even', 'get', 'her', 'head', 'through', 'the',
     'doorway'],
    ['oh', 'said', 'alice', 'how', 'i', 'wish', 'i', 'could', 'shut', 'up',
     'like', 'a', 'telescope'],
    ['i', 'think', 'i', 'could', 'if', 'i', 'only', 'knew', 'how', 'to',
     'begin'],
    ['alice', 'went', 'back', 'to', 'the', 'table', 'half', 'hoping', 'she',
     'might', 'find', 'another', 'key', 'on', 'it', 'or', 'at', 'any',
     'rate', 'a', 'book', 'of', 'rules', 'for', 'shutting', 'people', 'up',
     'like', 'telescopes'],
    ['this', 'time', 'she', 'found', 'a', 'little', 'bottle', 'on', 'it',
     '(which', 'certainly', 'was', 'not', 'here', 'before', 'said',
     'alice)', 'and', 'tied', 'round', 'the', 'neck', 'of', 'the', 'bottle',
     'was', 'a', 'paper', 'label', 'with', 'the', 'words', 'drink', 'me',
     'beautifully', 'printed', 'on', 'it', 'in', 'large', 'letters'],
    ['no', 'ill', 'look', 'first', 'she', 'said', 'and', 'see', 'whether',
     'its', 'marked', 'poison', 'or', 'not', 'for', 'she', 'had', 'never',
     'forgotten', 'that', 'if', 'you', 'drink', 'from', 'a', 'bottle',
     'marked', 'poison', 'it', 'is', 'almost', 'certain', 'to', 'disagree',
     'with', 'you', 'sooner', 'or', 'later'],
    ['however', 'this', 'bottle', 'was', 'not', 'marked', 'poison', 'so',
     'alice', 'ventured', 'to', 'taste', 'it', 'and', 'finding', 'it',
     'very', 'nice', '(it', 'had', 'a', 'sort', 'of', 'mixed', 'flavor',
     'of', 'cherrytart', 'custard', 'pineapple', 'roast', 'turkey', 'toffy',
     'and', 'hot', 'buttered', 'toast)', 'she', 'very', 'soon', 'finished',
     'it', 'off'],
    ['what', 'a', 'curious', 'feeling'],
    ['said', 'alice'],
    ['i', 'must', 'be', 'shutting', 'up', 'like', 'a', 'telescope'],
    ['and', 'so', 'it', 'was', 'indeed'],
    ['she', 'was', 'now', 'only', 'ten', 'inches', 'high', 'and', 'her',
     'face', 'brightened', 'up', 'at', 'the', 'thought', 'that', 'she',
     'was', 'now', 'the', 'right', 'size', 'for', 'going', 'through', 'the',
     'little', 'door', 'into', 'that', 'lovely', 'garden'],
    ['after', 'awhile', 'finding', 'that', 'nothing', 'more', 'happened',
     'she', 'decided', 'on', 'going', 'into', 'the', 'garden', 'at',
     'once;', 'but', 'alas', 'for', 'poor', 'alice'],
    ['when', 'she', 'got', 'to', 'the', 'door', 'she', 'found', 'she',
     'had', 'forgotten', 'the', 'little', 'golden', 'key', 'and', 'when',
     'she', 'went', 'back', 'to', 'the', 'table', 'for', 'it', 'she',
     'found', 'she', 'could', 'not', 'possibly', 'reach', 'it:', 'she',
     'could', 'see', 'it', 'quite', 'plainly', 'through', 'the', 'glass',
     'and', 'she', 'tried', 'her', 'best', 'to', 'climb', 'up', 'one', 'of',
     'the', 'legs', 'of', 'the', 'table', 'but', 'it', 'was', 'too',
     'slippery', 'and', 'when', 'she', 'had', 'tired', 'herself', 'out',
     'with', 'trying', 'the', 'poor', 'little', 'thing', 'sat', 'down',
     'and', 'cried'],
    ['come', 'theres', 'no', 'use', 'in', 'crying', 'like', 'that'],
    ['said', 'alice', 'to', 'herself', 'rather', 'sharply'],
    ['i', 'advise', 'you', 'to', 'leave', 'off', 'this', 'minute'],
    ['she', 'generally', 'gave', 'herself', 'very', 'good', 'advice',
     '(though', 'she', 'very', 'seldom', 'followed', 'it)', 'and',
     'sometimes', 'she', 'scolded', 'herself', 'so', 'severely', 'as', 'to',
     'bring', 'tears', 'into', 'her', 'eyes'],
    ['soon', 'her', 'eye', 'fell', 'on', 'a', 'little', 'glass', 'box',
     'that', 'was', 'lying', 'under', 'the', 'table:', 'she', 'opened',
     'it', 'and', 'found', 'in', 'it', 'a', 'very', 'small', 'cake', 'on',
     'which', 'the', 'words', 'eat', 'me', 'were', 'beautifully', 'marked',
     'in', 'currants'],
    ['well', 'ill', 'eat', 'it', 'said', 'alice', 'and', 'if', 'it',
     'makes', 'me', 'grow', 'larger', 'i', 'can', 'reach', 'the', 'key;',
     'and', 'if', 'it', 'makes', 'me', 'grow', 'smaller', 'i', 'can',
     'creep', 'under', 'the', 'door:', 'so', 'either', 'way', 'ill', 'get',
     'into', 'the', 'garden', 'and', 'i', 'dont', 'care', 'which',
     'happens'],
    ['she', 'ate', 'a', 'little', 'bit', 'and', 'said', 'anxiously', 'to',
     'herself', 'which', 'way'],
    ['which', 'way'],
    ['holding', 'her', 'hand', 'on', 'the', 'top', 'of', 'her', 'head',
     'to', 'feel', 'which', 'way', 'she', 'was', 'growing;', 'and', 'she',
     'was', 'quite', 'surprised', 'to', 'find', 'that', 'she', 'remained',
     'the', 'same', 'size'],
    ['so', 'she', 'set', 'to', 'work', 'and', 'very', 'soon', 'finished',
     'off', 'the', 'cake'],
    ['', 'iithe', 'pool', 'of', 'tears', 'curiouser', 'and', 'curiouser'],
    ['cried', 'alice', '(she', 'was', 'so', 'much', 'surprised', 'that',
     'for', 'the', 'moment', 'she', 'quite', 'forgot', 'how', 'to', 'speak',
     'good', 'english)'],
    ['now', 'im', 'opening', 'out', 'like', 'the', 'largest', 'telescope',
     'that', 'ever', 'was'],
    ['goodby', 'feet'],
    ['oh', 'my', 'poor', 'little', 'feet', 'i', 'wonder', 'who', 'will',
     'put', 'on', 'your', 'shoes', 'and', 'stockings', 'for', 'you', 'now',
     'dears'],
    ['i', 'shall', 'be', 'a', 'great', 'deal', 'too', 'far', 'off', 'to',
     'trouble', 'myself', 'about', 'you'],
    ['just', 'at', 'this', 'moment', 'her', 'head', 'struck', 'against',
     'the', 'roof', 'of', 'the', 'hall;', 'in', 'fact', 'she', 'was', 'now',
     'rather', 'more', 'than', 'nine', 'feet', 'high', 'and', 'she', 'at',
     'once', 'took', 'up', 'the', 'little', 'golden', 'key', 'and',
     'hurried', 'off', 'to', 'the', 'garden', 'door'],
    ['poor', 'alice'],
    ['it', 'was', 'as', 'much', 'as', 'she', 'could', 'do', 'lying', 'down',
     'on', 'one', 'side', 'to', 'look', 'through', 'into', 'the', 'garden',
     'with', 'one', 'eye;', 'but', 'to', 'get', 'through', 'was', 'more',
     'hopeless', 'than', 'ever'],
    ['she', 'sat', 'down', 'and', 'began', 'to', 'cry', 'again'],
    ['she', 'went', 'on', 'shedding', 'gallons', 'of', 'tears', 'until',
     'there', 'was', 'a', 'large', 'pool', 'all', 'round', 'her', 'and',
     'reaching', 'half', 'down', 'the', 'hall'],
    ['after', 'a', 'time', 'she', 'heard', 'a', 'little', 'pattering', 'of',
     'feet', 'in', 'the', 'distance', 'and', 'she', 'hastily', 'dried',
     'her', 'eyes', 'to', 'see', 'what', 'was', 'coming'],
    ['it', 'was', 'the', 'white', 'rabbit', 'returning', 'splendidly',
     'dressed', 'with', 'a', 'pair', 'of', 'white', 'kidgloves', 'in',
     'one', 'hand', 'and', 'a', 'large', 'fan', 'in', 'the', 'other'],
    ['he', 'came', 'trotting', 'along', 'in', 'a', 'great', 'hurry',
     'muttering', 'to', 'himself', 'oh'],
    ['the', 'duchess', 'the', 'duchess'],
    ['oh'],
    ['wont', 'she', 'be', 'savage', 'if', 'ive', 'kept', 'her', 'waiting'],
    ['when', 'the', 'rabbit', 'came', 'near', 'her', 'alice', 'began', 'in',
     'a', 'low', 'timid', 'voice', 'if', 'you', 'please', 'sir', 'the',
     'rabbit', 'started', 'violently', 'dropped', 'the', 'white',
     'kidgloves', 'and', 'the', 'fan', 'and', 'skurried', 'away', 'into',
     'the', 'darkness', 'as', 'hard', 'as', 'he', 'could', 'go'],
    ['', 'alice', 'took', 'up', 'the', 'fan', 'and', 'gloves', 'and', 'she',
     'kept', 'fanning', 'herself', 'all', 'the', 'time', 'she', 'went',
     'on', 'talking'],
    ['dear', 'dear'],
    ['how', 'queer', 'everything', 'is', 'today'],
    ['and', 'yesterday', 'things', 'went', 'on', 'just', 'as', 'usual'],
    ['was', 'i', 'the', 'same', 'when', 'i', 'got', 'up', 'this',
     'morning'],
    ['but', 'if', 'im', 'not', 'the', 'same', 'the', 'next', 'question',
     'is', 'who', 'in', 'the', 'world', 'am', 'i'],
    ['ah', 'thats', 'the', 'great', 'puzzle'],
    ['as', 'she', 'said', 'this', 'she', 'looked', 'down', 'at', 'her',
     'hands', 'and', 'was', 'surprised', 'to', 'see', 'that', 'she', 'had',
     'put', 'on', 'one', 'of', 'the', 'rabbits', 'little', 'white',
     'kidgloves', 'while', 'she', 'was', 'talking'],
    ['how', 'can', 'i', 'have', 'done', 'that'],
    ['she', 'thought'],
    ['i', 'must', 'be', 'growing', 'small', 'again'],
    ['she', 'got', 'up', 'and', 'went', 'to', 'the', 'table', 'to',
     'measure', 'herself', 'by', 'it', 'and', 'found', 'that', 'she', 'was',
     'now', 'about', 'two', 'feet', 'high', 'and', 'was', 'going', 'on',
     'shrinking', 'rapidly'],
    ['she', 'soon', 'found', 'out', 'that', 'the', 'cause', 'of', 'this',
     'was', 'the', 'fan', 'she', 'was', 'holding', 'and', 'she', 'dropped',
     'it', 'hastily', 'just', 'in', 'time', 'to', 'save', 'herself', 'from',
     'shrinking', 'away', 'altogether'],
    ['that', 'was', 'a', 'narrow', 'escape'],
    ['said', 'alice', 'a', 'good', 'deal', 'frightened', 'at', 'the',
     'sudden', 'change', 'but', 'very', 'glad', 'to', 'find', 'herself',
     'still', 'in', 'existence'],
    ['and', 'now', 'for', 'the', 'garden'],
    ['and', 'she', 'ran', 'with', 'all', 'speed', 'back', 'to', 'the',
     'little', 'door;', 'but', 'alas'],
    ['the', 'little', 'door', 'was', 'shut', 'again', 'and', 'the',
     'little', 'golden', 'key', 'was', 'lying', 'on', 'the', 'glass',
     'table', 'as', 'before'],
    ['things', 'are', 'worse', 'than', 'ever', 'thought', 'the', 'poor',
     'child', 'for', 'i', 'never', 'was', 'so', 'small', 'as', 'this',
     'before', 'never'],
    ['as', 'she', 'said', 'these', 'words', 'her', 'foot', 'slipped', 'and',
     'in', 'another', 'moment', 'splash'],
    ['she', 'was', 'up', 'to', 'her', 'chin', 'in', 'saltwater'],
    ['her', 'first', 'idea', 'was', 'that', 'she', 'had', 'somehow',
     'fallen', 'into', 'the', 'sea'],
    ['however', 'she', 'soon', 'made', 'out', 'that', 'she', 'was', 'in',
     'the', 'pool', 'of', 'tears', 'which', 'she', 'had', 'wept', 'when',
     'she', 'was', 'nine', 'feet', 'high'],
    ['', 'just', 'then', 'she', 'heard', 'something', 'splashing', 'about',
     'in', 'the', 'pool', 'a', 'little', 'way', 'off', 'and', 'she', 'swam',
     'nearer', 'to', 'see', 'what', 'it', 'was:', 'she', 'soon', 'made',
     'out', 'that', 'it', 'was', 'only', 'a', 'mouse', 'that', 'had',
     'slipped', 'in', 'like', 'herself'],
    ['would', 'it', 'be', 'of', 'any', 'use', 'now', 'thought', 'alice',
     'to', 'speak', 'to', 'this', 'mouse'],
    ['everything', 'is', 'so', 'outoftheway', 'down', 'here', 'that', 'i',
     'should', 'think', 'very', 'likely', 'it', 'can', 'talk;', 'at', 'any',
     'rate', 'theres', 'no', 'harm', 'in', 'trying'],
    ['so', 'she', 'began', 'o', 'mouse', 'do', 'you', 'know', 'the', 'way',
     'out', 'of', 'this', 'pool'],
    ['i', 'am', 'very', 'tired', 'of', 'swimming', 'about', 'here', 'o',
     'mouse'],
    ['the', 'mouse', 'looked', 'at', 'her', 'rather', 'inquisitively',
     'and', 'seemed', 'to', 'her', 'to', 'wink', 'with', 'one', 'of', 'its',
     'little', 'eyes', 'but', 'it', 'said', 'nothing'],
    ['perhaps', 'it', 'doesnt', 'understand', 'english', 'thought',
     'alice'],
    ['i', 'dare', 'say', 'its', 'a', 'french', 'mouse', 'come', 'over',
     'with', 'william', 'the', 'conqueror'],
    ['so', 'she', 'began', 'again:', 'ou', 'est', 'ma', 'chatte'],
    ['which', 'was', 'the', 'first', 'sentence', 'in', 'her', 'french',
     'lessonbook'],
    ['the', 'mouse', 'gave', 'a', 'sudden', 'leap', 'out', 'of', 'the',
     'water', 'and', 'seemed', 'to', 'quiver', 'all', 'over', 'with',
     'fright'],
    ['oh', 'i', 'beg', 'your', 'pardon'],
    ['cried', 'alice', 'hastily', 'afraid', 'that', 'she', 'had', 'hurt',
     'the', 'poor', 'animals', 'feelings'],
    ['i', 'quite', 'forgot', 'you', 'didnt', 'like', 'cats'],
    ['not', 'like', 'cats'],
    ['cried', 'the', 'mouse', 'in', 'a', 'shrill', 'passionate', 'voice'],
    ['would', 'you', 'like', 'cats', 'if', 'you', 'were', 'me'],
    ['well', 'perhaps', 'not', 'said', 'alice', 'in', 'a', 'soothing',
     'tone;', 'dont', 'be', 'angry', 'about', 'it'],
    ['and', 'yet', 'i', 'wish', 'i', 'could', 'show', 'you', 'our', 'cat',
     'dinah'],
    ['i', 'think', 'youd', 'take', 'a', 'fancy', 'to', 'cats', 'if', 'you',
     'could', 'only', 'see', 'her'],
    ['she', 'is', 'such', 'a', 'dear', 'quiet', 'thing'],
    ['the', 'mouse', 'was', 'bristling', 'all', 'over', 'and', 'she',
     'felt', 'certain', 'it', 'must', 'be', 'really', 'offended'],
    ['we', 'wont', 'talk', 'about', 'her', 'any', 'more', 'if', 'youd',
     'rather', 'not'],
    ['we', 'indeed'],
    ['cried', 'the', 'mouse', 'who', 'was', 'trembling', 'down', 'to',
     'the', 'end', 'of', 'its', 'tail'],
    ['as', 'if', 'i', 'would', 'talk', 'on', 'such', 'a', 'subject'],
    ['our', 'family', 'always', 'hated', 'catsnasty', 'low', 'vulgar',
     'things'],
    ['dont', 'let', 'me', 'hear', 'the', 'name', 'again'],
    ['', 'i', 'wont', 'indeed'],
    ['said', 'alice', 'in', 'a', 'great', 'hurry', 'to', 'change', 'the',
     'subject', 'of', 'conversation'],
    ['are', 'youare', 'you', 'fondofof', 'dogs'],
    ['there', 'is', 'such', 'a', 'nice', 'little', 'dog', 'near', 'our',
     'house', 'i', 'should', 'like', 'to', 'show', 'you'],
    ['it', 'kills', 'all', 'the', 'rats', 'andoh', 'dear'],
    ['cried', 'alice', 'in', 'a', 'sorrowful', 'tone'],
    ['im', 'afraid', 'ive', 'offended', 'it', 'again'],
    ['for', 'the', 'mouse', 'was', 'swimming', 'away', 'from', 'her', 'as',
     'hard', 'as', 'it', 'could', 'go', 'and', 'making', 'quite', 'a',
     'commotion', 'in', 'the', 'pool', 'as', 'it', 'went'],
    ['so', 'she', 'called', 'softly', 'after', 'it', 'mouse', 'dear'],
    ['do', 'come', 'back', 'again', 'and', 'we', 'wont', 'talk', 'about',
     'cats', 'or', 'dogs', 'either', 'if', 'you', 'dont', 'like', 'them'],
    ['when', 'the', 'mouse', 'heard', 'this', 'it', 'turned', 'round',
     'and', 'swam', 'slowly', 'back', 'to', 'her;', 'its', 'face', 'was',
     'quite', 'pale', 'and', 'it', 'said', 'in', 'a', 'low', 'trembling',
     'voice', 'let', 'us', 'get', 'to', 'the', 'shore', 'and', 'then',
     'ill', 'tell', 'you', 'my', 'history', 'and', 'youll', 'understand',
     'why', 'it', 'is', 'i', 'hate', 'cats', 'and', 'dogs'],
    ['it', 'was', 'high', 'time', 'to', 'go', 'for', 'the', 'pool', 'was',
     'getting', 'quite', 'crowded', 'with', 'the', 'birds', 'and',
     'animals', 'that', 'had', 'fallen', 'into', 'it;', 'there', 'were',
     'a', 'duck', 'and', 'a', 'dodo', 'a', 'lory', 'and', 'an', 'eaglet',
     'and', 'several', 'other', 'curious', 'creatures'],
    ['alice', 'led', 'the', 'way', 'and', 'the', 'whole', 'party', 'swam',
     'to', 'the', 'shore'],
    ['', 'iiia', 'caucusrace', 'and', 'a', 'long', 'tale', 'they', 'were',
     'indeed', 'a', 'queerlooking', 'party', 'that', 'assembled', 'on',
     'the', 'bankthe', 'birds', 'with', 'draggled', 'feathers', 'the',
     'animals', 'with', 'their', 'fur', 'clinging', 'close', 'to', 'them',
     'and', 'all', 'dripping', 'wet', 'cross', 'and', 'uncomfortable'],
    ['', 'the', 'first', 'question', 'of', 'course', 'was', 'how', 'to',
     'get', 'dry', 'again'],
    ['they', 'had', 'a', 'consultation', 'about', 'this', 'and', 'after',
     'a', 'few', 'minutes', 'it', 'seemed', 'quite', 'natural', 'to',
     'alice', 'to', 'find', 'herself', 'talking', 'familiarly', 'with',
     'them', 'as', 'if', 'she', 'had', 'known', 'them', 'all', 'her',
     'life'],
    ['at', 'last', 'the', 'mouse', 'who', 'seemed', 'to', 'be', 'a',
     'person', 'of', 'some', 'authority', 'among', 'them', 'called', 'out',
     'sit', 'down', 'all', 'of', 'you', 'and', 'listen', 'to', 'me'],
    ['ill', 'soon', 'make', 'you', 'dry', 'enough'],
    ['they', 'all', 'sat', 'down', 'at', 'once', 'in', 'a', 'large', 'ring',
     'with', 'the', 'mouse', 'in', 'the', 'middle'],
    ['ahem'],
    ['said', 'the', 'mouse', 'with', 'an', 'important', 'air'],
    ['are', 'you', 'all', 'ready'],
    ['this', 'is', 'the', 'driest', 'thing', 'i', 'know'],
    ['silence', 'all', 'round', 'if', 'you', 'please'],
    ['william', 'the', 'conqueror', 'whose', 'cause', 'was', 'favored',
     'by', 'the', 'pope', 'was', 'soon', 'submitted', 'to', 'by', 'the',
     'english', 'who', 'wanted', 'leaders', 'and', 'had', 'been', 'of',
     'late', 'much', 'accustomed', 'to', 'usurpation', 'and', 'conquest'],
    ['edwin', 'and', 'morcar', 'the', 'earls', 'of', 'mercia', 'and',
     'northumbria', 'ugh'],
    ['said', 'the', 'lory', 'with', 'a', 'shiver'],
    ['and', 'even', 'stigand', 'the', 'patriotic', 'archbishop', 'of',
     'canterbury', 'found', 'it', 'advisable', 'found', 'what'],
    ['said', 'the', 'duck'],
    ['found', 'it', 'the', 'mouse', 'replied', 'rather', 'crossly;', 'of',
     'course', 'you', 'know', 'what', 'it', 'means'],
    ['i', 'know', 'what', 'it', 'means', 'well', 'enough', 'when', 'i',
     'find', 'a', 'thing', 'said', 'the', 'duck;', 'its', 'generally', 'a',
     'frog', 'or', 'a', 'worm'],
    ['the', 'question', 'is', 'what', 'did', 'the', 'archbishop', 'find'],
    ['the', 'mouse', 'did', 'not', 'notice', 'this', 'question', 'but',
     'hurriedly', 'went', 'on', 'found', 'it', 'advisable', 'to', 'go',
     'with', 'edgar', 'atheling', 'to', 'meet', 'william', 'and', 'offer',
     'him', 'the', 'crown'],
    ['how', 'are', 'you', 'getting', 'on', 'now', 'my', 'dear'],
    ['it', 'continued', 'turning', 'to', 'alice', 'as', 'it', 'spoke'],
    ['as', 'wet', 'as', 'ever', 'said', 'alice', 'in', 'a', 'melancholy',
     'tone;', 'it', 'doesnt', 'seem', 'to', 'dry', 'me', 'at', 'all'],
    ['in', 'that', 'case', 'said', 'the', 'dodo', 'solemnly', 'rising',
     'to', 'its', 'feet', 'i', 'move', 'that', 'the', 'meeting', 'adjourn',
     'for', 'the', 'immediate', 'adoption', 'of', 'more', 'energetic',
     'remedies', 'speak', 'english'],
    ['said', 'the', 'eaglet'],
    ['i', 'dont', 'know', 'the', 'meaning', 'of', 'half', 'those', 'long',
     'words', 'and', 'whats', 'more', 'i', 'dont', 'believe', 'you', 'do',
     'either'],
    ['what', 'i', 'was', 'going', 'to', 'say', 'said', 'the', 'dodo', 'in',
     'an', 'offended', 'tone', 'is', 'that', 'the', 'best', 'thing', 'to',
     'get', 'us', 'dry', 'would', 'be', 'a', 'caucusrace'],
    ['what', 'is', 'a', 'caucusrace'],
    ['said', 'alice'],
    ['', 'why', 'said', 'the', 'dodo', 'the', 'best', 'way', 'to',
     'explain', 'it', 'is', 'to', 'do', 'it'],
    ['first', 'it', 'marked', 'out', 'a', 'racecourse', 'in', 'a', 'sort',
     'of', 'circle', 'and', 'then', 'all', 'the', 'party', 'were', 'placed',
     'along', 'the', 'course', 'here', 'and', 'there'],
    ['there', 'was', 'no', 'one', 'two', 'three', 'and', 'away'],
    ['but', 'they', 'began', 'running', 'when', 'they', 'liked', 'and',
     'left', 'off', 'when', 'they', 'liked', 'so', 'that', 'it', 'was',
     'not', 'easy', 'to', 'know', 'when', 'the', 'race', 'was', 'over'],
    ['however', 'when', 'they', 'had', 'been', 'running', 'half', 'an',
     'hour', 'or', 'so', 'and', 'were', 'quite', 'dry', 'again', 'the',
     'dodo', 'suddenly', 'called', 'out', 'the', 'race', 'is', 'over'],
    ['and', 'they', 'all', 'crowded', 'round', 'it', 'panting', 'and',
     'asking', 'but', 'who', 'has', 'won'],
    ['this', 'question', 'the', 'dodo', 'could', 'not', 'answer', 'without',
     'a', 'great', 'deal', 'of', 'thought'],
    ['at', 'last', 'it', 'said', 'everybody', 'has', 'won', 'and', 'all',
     'must', 'have', 'prizes'],
    ['but', 'who', 'is', 'to', 'give', 'the', 'prizes'],
    ['quite', 'a', 'chorus', 'of', 'voices', 'asked'],
    ['why', 'she', 'of', 'course', 'said', 'the', 'dodo', 'pointing', 'to',
     'alice', 'with', 'one', 'finger;', 'and', 'the', 'whole', 'party',
     'at', 'once', 'crowded', 'round', 'her', 'calling', 'out', 'in', 'a',
     'confused', 'way', 'prizes'],
    ['prizes'],
    ['alice', 'had', 'no', 'idea', 'what', 'to', 'do', 'and', 'in',
     'despair', 'she', 'put', 'her', 'hand', 'into', 'her', 'pocket', 'and',
     'pulled', 'out', 'a', 'box', 'of', 'comfits', '(luckily', 'the',
     'saltwater', 'had', 'not', 'got', 'into', 'it)', 'and', 'handed',
     'them', 'round', 'as', 'prizes'],
    ['there', 'was', 'exactly', 'one', 'apiece', 'all', 'round'],
    ['the', 'next', 'thing', 'was', 'to', 'eat', 'the', 'comfits;', 'this',
     'caused', 'some', 'noise', 'and', 'confusion', 'as', 'the', 'large',
     'birds', 'complained', 'that', 'they', 'could', 'not', 'taste',
     'theirs', 'and', 'the', 'small', 'ones', 'choked', 'and', 'had', 'to',
     'be', 'patted', 'on', 'the', 'back'],
    ['however', 'it', 'was', 'over', 'at', 'last', 'and', 'they', 'sat',
     'down', 'again', 'in', 'a', 'ring', 'and', 'begged', 'the', 'mouse',
     'to', 'tell', 'them', 'something', 'more'],
    ['you', 'promised', 'to', 'tell', 'me', 'your', 'history', 'you',
     'know', 'said', 'alice', 'and', 'why', 'it', 'is', 'you', 'hatec',
     'and', 'd', 'she', 'added', 'in', 'a', 'whisper', 'half', 'afraid',
     'that', 'it', 'would', 'be', 'offended', 'again'],
    ['mine', 'is', 'a', 'long', 'and', 'a', 'sad', 'tale'],
    ['said', 'the', 'mouse', 'turning', 'to', 'alice', 'and', 'sighing'],
    ['it', 'is', 'a', 'long', 'tail', 'certainly', 'said', 'alice',
     'looking', 'down', 'with', 'wonder', 'at', 'the', 'mouses', 'tail',
     'but', 'why', 'do', 'you', 'call', 'it', 'sad'],
    ['and', 'she', 'kept', 'on', 'puzzling', 'about', 'it', 'while', 'the',
     'mouse', 'was', 'speaking', 'so', 'that', 'her', 'idea', 'of', 'the',
     'tale', 'was', 'something', 'like', 'this:', 'fury', 'said', 'to', 'a',
     'mouse', 'that', 'he', 'met', 'in', 'the', 'house', 'let', 'us',
     'both', 'go', 'to', 'law:', 'i', 'will', 'prosecute', 'you'],
    ['', 'come', 'ill', 'take', 'no', 'denial:', 'we', 'must', 'have',
     'the', 'trial;', 'for', 'really', 'this', 'morning', 'ive', 'nothing',
     'to', 'do'],
    ['', 'said', 'the', 'mouse', 'to', 'the', 'cur', 'such', 'a', 'trial',
     'dear', 'sir', 'with', 'no', 'jury', 'or', 'judge', 'would', 'be',
     'wasting', 'our', 'breath'],
    ['', 'ill', 'be', 'judge', 'ill', 'be', 'jury', 'said', 'cunning',
     'old', 'fury;', 'ill', 'try', 'the', 'whole', 'cause', 'and',
     'condemn', 'you', 'to', 'death'],
    ['you', 'are', 'not', 'attending'],
    ['said', 'the', 'mouse', 'to', 'alice', 'severely'],
    ['what', 'are', 'you', 'thinking', 'of'],
    ['i', 'beg', 'your', 'pardon', 'said', 'alice', 'very', 'humbly', 'you',
     'had', 'got', 'to', 'the', 'fifth', 'bend', 'i', 'think'],
    ['you', 'insult', 'me', 'by', 'talking', 'such', 'nonsense'],
    ['said', 'the', 'mouse', 'getting', 'up', 'and', 'walking', 'away'],
    ['please', 'come', 'back', 'and', 'finish', 'your', 'story'],
    ['alice', 'called', 'after', 'it'],
    ['and', 'the', 'others', 'all', 'joined', 'in', 'chorus', 'yes',
     'please', 'do'],
    ['but', 'the', 'mouse', 'only', 'shook', 'its', 'head', 'impatiently',
     'and', 'walked', 'a', 'little', 'quicker'],
    ['i', 'wish', 'i', 'had', 'dinah', 'our', 'cat', 'here'],
    ['said', 'alice'],
    ['this', 'caused', 'a', 'remarkable', 'sensation', 'among', 'the',
     'party'],
    ['some', 'of', 'the', 'birds', 'hurried', 'off', 'at', 'once', 'and',
     'a', 'canary', 'called', 'out', 'in', 'a', 'trembling', 'voice', 'to',
     'its', 'children', 'come', 'away', 'my', 'dears'],
    ['its', 'high', 'time', 'you', 'were', 'all', 'in', 'bed'],
    ['on', 'various', 'pretexts', 'they', 'all', 'moved', 'off', 'and',
     'alice', 'was', 'soon', 'left', 'alone'],
    ['i', 'wish', 'i', 'hadnt', 'mentioned', 'dinah'],
    ['nobody', 'seems', 'to', 'like', 'her', 'down', 'here', 'and', 'im',
     'sure', 'shes', 'the', 'best', 'cat', 'in', 'the', 'world'],
    ['poor', 'alice', 'began', 'to', 'cry', 'again', 'for', 'she', 'felt',
     'very', 'lonely', 'and', 'lowspirited'],
    ['in', 'a', 'little', 'while', 'however', 'she', 'again', 'heard', 'a',
     'little', 'pattering', 'of', 'footsteps', 'in', 'the', 'distance',
     'and', 'she', 'looked', 'up', 'eagerly'],
    ['', 'ivthe', 'rabbit', 'sends', 'in', 'a', 'little', 'bill', 'it',
     'was', 'the', 'white', 'rabbit', 'trotting', 'slowly', 'back', 'again',
     'and', 'looking', 'anxiously', 'about', 'as', 'it', 'went', 'as', 'if',
     'it', 'had', 'lost', 'something;', 'alice', 'heard', 'it', 'muttering',
     'to', 'itself', 'the', 'duchess'],
    ['the', 'duchess'],
    ['oh', 'my', 'dear', 'paws'],
    ['oh', 'my', 'fur', 'and', 'whiskers'],
    ['shell', 'get', 'me', 'executed', 'as', 'sure', 'as', 'ferrets', 'are',
     'ferrets'],
    ['where', 'can', 'i', 'have', 'dropped', 'them', 'i', 'wonder'],
    ['alice', 'guessed', 'in', 'a', 'moment', 'that', 'it', 'was',
     'looking', 'for', 'the', 'fan', 'and', 'the', 'pair', 'of', 'white',
     'kidgloves', 'and', 'she', 'very', 'goodnaturedly', 'began', 'hunting',
     'about', 'for', 'them', 'but', 'they', 'were', 'nowhere', 'to', 'be',
     'seeneverything', 'seemed', 'to', 'have', 'changed', 'since', 'her',
     'swim', 'in', 'the', 'pool', 'and', 'the', 'great', 'hall', 'with',
     'the', 'glass', 'table', 'and', 'the', 'little', 'door', 'had',
     'vanished', 'completely'],
    ['very', 'soon', 'the', 'rabbit', 'noticed', 'alice', 'and', 'called',
     'to', 'her', 'in', 'an', 'angry', 'tone', 'why', 'mary', 'ann', 'what',
     'are', 'you', 'doing', 'out', 'here'],
    ['run', 'home', 'this', 'moment', 'and', 'fetch', 'me', 'a', 'pair',
     'of', 'gloves', 'and', 'a', 'fan'],
    ['quick', 'now'],
    ['he', 'took', 'me', 'for', 'his', 'housemaid'],
    ['said', 'alice', 'as', 'she', 'ran', 'off'],
    ['how', 'surprised', 'hell', 'be', 'when', 'he', 'finds', 'out', 'who',
     'i', 'am'],
    ['as', 'she', 'said', 'this', 'she', 'came', 'upon', 'a', 'neat',
     'little', 'house', 'on', 'the', 'door', 'of', 'which', 'was', 'a',
     'bright', 'brass', 'plate', 'with', 'the', 'name', 'w'],
    ['rabbit', 'engraved', 'upon', 'it'],
    ['she', 'went', 'in', 'without', 'knocking', 'and', 'hurried',
     'upstairs', 'in', 'great', 'fear', 'lest', 'she', 'should', 'meet',
     'the', 'real', 'mary', 'ann', 'and', 'be', 'turned', 'out', 'of',
     'the', 'house', 'before', 'she', 'had', 'found', 'the', 'fan', 'and',
     'gloves'],
    ['by', 'this', 'time', 'alice', 'had', 'found', 'her', 'way', 'into',
     'a', 'tidy', 'little', 'room', 'with', 'a', 'table', 'in', 'the',
     'window', 'and', 'on', 'it', 'a', 'fan', 'and', 'two', 'or', 'three',
     'pairs', 'of', 'tiny', 'white', 'kidgloves;', 'she', 'took', 'up',
     'the', 'fan', 'and', 'a', 'pair', 'of', 'the', 'gloves', 'and', 'was',
     'just', 'going', 'to', 'leave', 'the', 'room', 'when', 'her', 'eyes',
     'fell', 'upon', 'a', 'little', 'bottle', 'that', 'stood', 'near',
     'the', 'lookingglass'],
    ['she', 'uncorked', 'it', 'and', 'put', 'it', 'to', 'her', 'lips',
     'saying', 'to', 'herself', 'i', 'do', 'hope', 'itll', 'make', 'me',
     'grow', 'large', 'again', 'for', 'really', 'im', 'quite', 'tired',
     'of', 'being', 'such', 'a', 'tiny', 'little', 'thing'],
    ['before', 'she', 'had', 'drunk', 'half', 'the', 'bottle', 'she',
     'found', 'her', 'head', 'pressing', 'against', 'the', 'ceiling', 'and',
     'had', 'to', 'stoop', 'to', 'save', 'her', 'neck', 'from', 'being',
     'broken'],
    ['she', 'hastily', 'put', 'down', 'the', 'bottle', 'remarking', 'thats',
     'quite', 'enoughi', 'hope', 'i', 'shant', 'grow', 'any', 'more'],
    ['alas'],
    ['it', 'was', 'too', 'late', 'to', 'wish', 'that'],
    ['she', 'went', 'on', 'growing', 'and', 'growing', 'and', 'very',
     'soon', 'she', 'had', 'to', 'kneel', 'down', 'on', 'the', 'floor'],
    ['still', 'she', 'went', 'on', 'growing', 'and', 'as', 'a', 'last',
     'resource', 'she', 'put', 'one', 'arm', 'out', 'of', 'the', 'window',
     'and', 'one', 'foot', 'up', 'the', 'chimney', 'and', 'said', 'to',
     'herself', 'now', 'i', 'can', 'do', 'no', 'more', 'whatever',
     'happens'],
    ['what', 'will', 'become', 'of', 'me'],
    ['', 'luckily', 'for', 'alice', 'the', 'little', 'magic', 'bottle',
     'had', 'now', 'had', 'its', 'full', 'effect', 'and', 'she', 'grew',
     'no', 'larger'],
    ['after', 'a', 'few', 'minutes', 'she', 'heard', 'a', 'voice',
     'outside', 'and', 'stopped', 'to', 'listen'],
    ['mary', 'ann'],
    ['mary', 'ann'],
    ['said', 'the', 'voice'],
    ['fetch', 'me', 'my', 'gloves', 'this', 'moment'],
    ['then', 'came', 'a', 'little', 'pattering', 'of', 'feet', 'on', 'the',
     'stairs'],
    ['alice', 'knew', 'it', 'was', 'the', 'rabbit', 'coming', 'to', 'look',
     'for', 'her', 'and', 'she', 'trembled', 'till', 'she', 'shook', 'the',
     'house', 'quite', 'forgetting', 'that', 'she', 'was', 'now', 'about',
     'a', 'thousand', 'times', 'as', 'large', 'as', 'the', 'rabbit', 'and',
     'had', 'no', 'reason', 'to', 'be', 'afraid', 'of', 'it'],
    ['presently', 'the', 'rabbit', 'came', 'up', 'to', 'the', 'door', 'and',
     'tried', 'to', 'open', 'it;', 'but', 'as', 'the', 'door', 'opened',
     'inwards', 'and', 'alices', 'elbow', 'was', 'pressed', 'hard',
     'against', 'it', 'that', 'attempt', 'proved', 'a', 'failure'],
    ['alice', 'heard', 'it', 'say', 'to', 'itself', 'then', 'ill', 'go',
     'round', 'and', 'get', 'in', 'at', 'the', 'window'],
    ['that', 'you', 'wont'],
    ['thought', 'alice;', 'and', 'after', 'waiting', 'till', 'she',
     'fancied', 'she', 'heard', 'the', 'rabbit', 'just', 'under', 'the',
     'window', 'she', 'suddenly', 'spread', 'out', 'her', 'hand', 'and',
     'made', 'a', 'snatch', 'in', 'the', 'air'],
    ['she', 'did', 'not', 'get', 'hold', 'of', 'anything', 'but', 'she',
     'heard', 'a', 'little', 'shriek', 'and', 'a', 'fall', 'and', 'a',
     'crash', 'of', 'broken', 'glass', 'from', 'which', 'she', 'concluded',
     'that', 'it', 'was', 'just', 'possible', 'it', 'had', 'fallen', 'into',
     'a', 'cucumberframe', 'or', 'something', 'of', 'that', 'sort'],
    ['next', 'came', 'an', 'angry', 'voicethe', 'rabbitspat'],
    ['pat'],
    ['where', 'are', 'you'],
    ['and', 'then', 'a', 'voice', 'she', 'had', 'never', 'heard', 'before',
     'sure', 'then', 'im', 'here'],
    ['digging', 'for', 'apples', 'yer', 'honor'],
    ['here'],
    ['come', 'and', 'help', 'me', 'out', 'of', 'this'],
    ['now', 'tell', 'me', 'pat', 'whats', 'that', 'in', 'the', 'window'],
    ['sure', 'its', 'an', 'arm', 'yer', 'honor'],
    ['well', 'its', 'got', 'no', 'business', 'there', 'at', 'any', 'rate;',
     'go', 'and', 'take', 'it', 'away'],
    ['there', 'was', 'a', 'long', 'silence', 'after', 'this', 'and',
     'alice', 'could', 'only', 'hear', 'whispers', 'now', 'and', 'then',
     'and', 'at', 'last', 'she', 'spread', 'out', 'her', 'hand', 'again',
     'and', 'made', 'another', 'snatch', 'in', 'the', 'air'],
    ['this', 'time', 'there', 'were', 'two', 'little', 'shrieks', 'and',
     'more', 'sounds', 'of', 'broken', 'glass'],
    ['i', 'wonder', 'what', 'theyll', 'do', 'next'],
    ['thought', 'alice'],
    ['as', 'for', 'pulling', 'me', 'out', 'of', 'the', 'window', 'i',
     'only', 'wish', 'they', 'could'],
    ['she', 'waited', 'for', 'some', 'time', 'without', 'hearing',
     'anything', 'more'],
    ['at', 'last', 'came', 'a', 'rumbling', 'of', 'little', 'cartwheels',
     'and', 'the', 'sound', 'of', 'a', 'good', 'many', 'voices', 'all',
     'talking', 'together'],
    ['she', 'made', 'out', 'the', 'words:', 'wheres', 'the', 'other',
     'ladder'],
    ['bills', 'got', 'the', 'otherbill'],
    ['here', 'bill'],
    ['will', 'the', 'roof', 'bear'],
    ['whos', 'to', 'go', 'down', 'the', 'chimney'],
    ['nay', 'i', 'shant'],
    ['you', 'do', 'it'],
    ['here', 'bill'],
    ['the', 'master', 'says', 'youve', 'got', 'to', 'go', 'down', 'the',
     'chimney'],
    ['alice', 'drew', 'her', 'foot', 'as', 'far', 'down', 'the', 'chimney',
     'as', 'she', 'could', 'and', 'waited', 'till', 'she', 'heard', 'a',
     'little', 'animal', 'scratching', 'and', 'scrambling', 'about', 'in',
     'the', 'chimney', 'close', 'above', 'her;', 'then', 'she', 'gave',
     'one', 'sharp', 'kick', 'and', 'waited', 'to', 'see', 'what', 'would',
     'happen', 'next'],
    ['the', 'first', 'thing', 'she', 'heard', 'was', 'a', 'general',
     'chorus', 'of', 'there', 'goes', 'bill'],
    ['then', 'the', 'rabbits', 'voice', 'alonecatch', 'him', 'you', 'by',
     'the', 'hedge'],
    ['then', 'silence', 'and', 'then', 'another', 'confusion', 'of',
     'voiceshold', 'up', 'his', 'headbrandy', 'nowdont', 'choke', 'himwhat',
     'happened', 'to', 'you'],
    ['last', 'came', 'a', 'little', 'feeble', 'squeaking', 'voice', 'well',
     'i', 'hardly', 'knowno', 'more', 'thank', 'ye'],
    ['im', 'better', 'nowall', 'i', 'know', 'is', 'something', 'comes',
     'at', 'me', 'like', 'a', 'jackinthebox', 'and', 'up', 'i', 'goes',
     'like', 'a', 'skyrocket'],
    ['after', 'a', 'minute', 'or', 'two', 'of', 'silence', 'they', 'began',
     'moving', 'about', 'again', 'and', 'alice', 'heard', 'the', 'rabbit',
     'say', 'a', 'barrowful', 'will', 'do', 'to', 'begin', 'with'],
    ['a', 'barrowful', 'of', 'what'],
    ['thought', 'alice'],
    ['but', 'she', 'had', 'not', 'long', 'to', 'doubt', 'for', 'the',
     'next', 'moment', 'a', 'shower', 'of', 'little', 'pebbles', 'came',
     'rattling', 'in', 'at', 'the', 'window', 'and', 'some', 'of', 'them',
     'hit', 'her', 'in', 'the', 'face'],
    ['alice', 'noticed', 'with', 'some', 'surprise', 'that', 'the',
     'pebbles', 'were', 'all', 'turning', 'into', 'little', 'cakes', 'as',
     'they', 'lay', 'on', 'the', 'floor', 'and', 'a', 'bright', 'idea',
     'came', 'into', 'her', 'head'],
    ['if', 'i', 'eat', 'one', 'of', 'these', 'cakes', 'she', 'thought',
     'its', 'sure', 'to', 'make', 'some', 'change', 'in', 'my', 'size'],
    ['so', 'she', 'swallowed', 'one', 'of', 'the', 'cakes', 'and', 'was',
     'delighted', 'to', 'find', 'that', 'she', 'began', 'shrinking',
     'directly'],
    ['as', 'soon', 'as', 'she', 'was', 'small', 'enough', 'to', 'get',
     'through', 'the', 'door', 'she', 'ran', 'out', 'of', 'the', 'house',
     'and', 'found', 'quite', 'a', 'crowd', 'of', 'little', 'animals',
     'and', 'birds', 'waiting', 'outside'],
    ['they', 'all', 'made', 'a', 'rush', 'at', 'alice', 'the', 'moment',
     'she', 'appeared', 'but', 'she', 'ran', 'off', 'as', 'hard', 'as',
     'she', 'could', 'and', 'soon', 'found', 'herself', 'safe', 'in', 'a',
     'thick', 'wood'],
    ['[illustration:', 'the', 'duchess', 'tucked', 'her', 'arm',
     'affectionately', 'into', 'alices'],
    [']', 'the', 'first', 'thing', 'ive', 'got', 'to', 'do', 'said',
     'alice', 'to', 'herself', 'as', 'she', 'wandered', 'about', 'in',
     'the', 'wood', 'is', 'to', 'grow', 'to', 'my', 'right', 'size',
     'again;', 'and', 'the', 'second', 'thing', 'is', 'to', 'find', 'my',
     'way', 'into', 'that', 'lovely', 'garden'],
    ['i', 'suppose', 'i', 'ought', 'to', 'eat', 'or', 'drink', 'something',
     'or', 'other', 'but', 'the', 'great', 'question', 'is', 'what'],
    ['alice', 'looked', 'all', 'around', 'her', 'at', 'the', 'flowers',
     'and', 'the', 'blades', 'of', 'grass', 'but', 'she', 'could', 'not',
     'see', 'anything', 'that', 'looked', 'like', 'the', 'right', 'thing',
     'to', 'eat', 'or', 'drink', 'under', 'the', 'circumstances'],
    ['there', 'was', 'a', 'large', 'mushroom', 'growing', 'near', 'her',
     'about', 'the', 'same', 'height', 'as', 'herself'],
    ['she', 'stretched', 'herself', 'up', 'on', 'tiptoe', 'and', 'peeped',
     'over', 'the', 'edge', 'and', 'her', 'eyes', 'immediately', 'met',
     'those', 'of', 'a', 'large', 'blue', 'caterpillar', 'that', 'was',
     'sitting', 'on', 'the', 'top', 'with', 'its', 'arms', 'folded',
     'quietly', 'smoking', 'a', 'long', 'hookah', 'and', 'taking', 'not',
     'the', 'smallest', 'notice', 'of', 'her', 'or', 'of', 'anything',
     'else'],
    ['', 'vadvice', 'from', 'a', 'caterpillar', 'at', 'last', 'the',
     'caterpillar', 'took', 'the', 'hookah', 'out', 'of', 'its', 'mouth',
     'and', 'addressed', 'alice', 'in', 'a', 'languid', 'sleepy', 'voice'],
    ['who', 'are', 'you'],
    ['said', 'the', 'caterpillar'],
    ['', 'alice', 'replied', 'rather', 'shyly', 'ii', 'hardly', 'know',
     'sir', 'just', 'at', 'presentat', 'least', 'i', 'know', 'who', 'i',
     'was', 'when', 'i', 'got', 'up', 'this', 'morning', 'but', 'i',
     'think', 'i', 'must', 'have', 'changed', 'several', 'times', 'since',
     'then'],
    ['what', 'do', 'you', 'mean', 'by', 'that'],
    ['said', 'the', 'caterpillar', 'sternly'],
    ['explain', 'yourself'],
    ['i', 'cant', 'explain', 'myself', 'im', 'afraid', 'sir', 'said',
     'alice', 'because', 'im', 'not', 'myself', 'you', 'seebeing', 'so',
     'many', 'different', 'sizes', 'in', 'a', 'day', 'is', 'very',
     'confusing'],
    ['she', 'drew', 'herself', 'up', 'and', 'said', 'very', 'gravely', 'i',
     'think', 'you', 'ought', 'to', 'tell', 'me', 'who', 'you', 'are',
     'first'],
    ['why'],
    ['said', 'the', 'caterpillar'],
    ['as', 'alice', 'could', 'not', 'think', 'of', 'any', 'good', 'reason',
     'and', 'the', 'caterpillar', 'seemed', 'to', 'be', 'in', 'a', 'very',
     'unpleasant', 'state', 'of', 'mind', 'she', 'turned', 'away'],
    ['come', 'back'],
    ['the', 'caterpillar', 'called', 'after', 'her'],
    ['ive', 'something', 'important', 'to', 'say'],
    ['alice', 'turned', 'and', 'came', 'back', 'again'],
    ['keep', 'your', 'temper', 'said', 'the', 'caterpillar'],
    ['is', 'that', 'all'],
    ['said', 'alice', 'swallowing', 'down', 'her', 'anger', 'as', 'well',
     'as', 'she', 'could'],
    ['no', 'said', 'the', 'caterpillar'],
    ['it', 'unfolded', 'its', 'arms', 'took', 'the', 'hookah', 'out', 'of',
     'its', 'mouth', 'again', 'and', 'said', 'so', 'you', 'think', 'youre',
     'changed', 'do', 'you'],
    ['im', 'afraid', 'i', 'am', 'sir', 'said', 'alice'],
    ['i', 'cant', 'remember', 'things', 'as', 'i', 'usedand', 'i', 'dont',
     'keep', 'the', 'same', 'size', 'for', 'ten', 'minutes', 'together'],
    ['what', 'size', 'do', 'you', 'want', 'to', 'be'],
    ['asked', 'the', 'caterpillar'],
    ['oh', 'im', 'not', 'particular', 'as', 'to', 'size', 'alice',
     'hastily', 'replied', 'only', 'one', 'doesnt', 'like', 'changing',
     'so', 'often', 'you', 'know'],
    ['i', 'should', 'like', 'to', 'be', 'a', 'little', 'larger', 'sir',
     'if', 'you', 'wouldnt', 'mind', 'said', 'alice'],
    ['three', 'inches', 'is', 'such', 'a', 'wretched', 'height', 'to',
     'be'],
    ['it', 'is', 'a', 'very', 'good', 'height', 'indeed'],
    ['said', 'the', 'caterpillar', 'angrily', 'rearing', 'itself',
     'upright', 'as', 'it', 'spoke', '(it', 'was', 'exactly', 'three',
     'inches', 'high)'],
    ['in', 'a', 'minute', 'or', 'two', 'the', 'caterpillar', 'got', 'down',
     'off', 'the', 'mushroom', 'and', 'crawled', 'away', 'into', 'the',
     'grass', 'merely', 'remarking', 'as', 'it', 'went', 'one', 'side',
     'will', 'make', 'you', 'grow', 'taller', 'and', 'the', 'other', 'side',
     'will', 'make', 'you', 'grow', 'shorter'],
    ['one', 'side', 'of', 'what'],
    ['the', 'other', 'side', 'of', 'what'],
    ['thought', 'alice', 'to', 'herself'],
    ['of', 'the', 'mushroom', 'said', 'the', 'caterpillar', 'just', 'as',
     'if', 'she', 'had', 'asked', 'it', 'aloud;', 'and', 'in', 'another',
     'moment', 'it', 'was', 'out', 'of', 'sight'],
    ['alice', 'remained', 'looking', 'thoughtfully', 'at', 'the',
     'mushroom', 'for', 'a', 'minute', 'trying', 'to', 'make', 'out',
     'which', 'were', 'the', 'two', 'sides', 'of', 'it'],
    ['at', 'last', 'she', 'stretched', 'her', 'arms', 'round', 'it', 'as',
     'far', 'as', 'they', 'would', 'go', 'and', 'broke', 'off', 'a', 'bit',
     'of', 'the', 'edge', 'with', 'each', 'hand'],
    ['and', 'now', 'which', 'is', 'which'],
    ['she', 'said', 'to', 'herself', 'and', 'nibbled', 'a', 'little', 'of',
     'the', 'righthand', 'bit', 'to', 'try', 'the', 'effect'],
    ['the', 'next', 'moment', 'she', 'felt', 'a', 'violent', 'blow',
     'underneath', 'her', 'chinit', 'had', 'struck', 'her', 'foot'],
    ['she', 'was', 'a', 'good', 'deal', 'frightened', 'by', 'this', 'very',
     'sudden', 'change', 'as', 'she', 'was', 'shrinking', 'rapidly;', 'so',
     'she', 'set', 'to', 'work', 'at', 'once', 'to', 'eat', 'some', 'of',
     'the', 'other', 'bit'],
    ['her', 'chin', 'was', 'pressed', 'so', 'closely', 'against', 'her',
     'foot', 'that', 'there', 'was', 'hardly', 'room', 'to', 'open', 'her',
     'mouth;', 'but', 'she', 'did', 'it', 'at', 'last', 'and', 'managed',
     'to', 'swallow', 'a', 'morsel', 'of', 'the', 'lefthand', 'bit'],
    ['come', 'my', 'heads', 'free', 'at', 'last'],
    ['said', 'alice;', 'but', 'all', 'she', 'could', 'see', 'when', 'she',
     'looked', 'down', 'was', 'an', 'immense', 'length', 'of', 'neck',
     'which', 'seemed', 'to', 'rise', 'like', 'a', 'stalk', 'out', 'of',
     'a', 'sea', 'of', 'green', 'leaves', 'that', 'lay', 'far', 'below',
     'her'],
    ['where', 'have', 'my', 'shoulders', 'got', 'to'],
    ['and', 'oh', 'my', 'poor', 'hands', 'how', 'is', 'it', 'i', 'cant',
     'see', 'you'],
    ['she', 'was', 'delighted', 'to', 'find', 'that', 'her', 'neck',
     'would', 'bend', 'about', 'easily', 'in', 'any', 'direction', 'like',
     'a', 'serpent'],
    ['she', 'had', 'just', 'succeeded', 'in', 'curving', 'it', 'down',
     'into', 'a', 'graceful', 'zigzag', 'and', 'was', 'going', 'to', 'dive',
     'in', 'among', 'the', 'leaves', 'when', 'a', 'sharp', 'hiss', 'made',
     'her', 'draw', 'back', 'in', 'a', 'hurrya', 'large', 'pigeon', 'had',
     'flown', 'into', 'her', 'face', 'and', 'was', 'beating', 'her',
     'violently', 'with', 'its', 'wings'],
    ['', 'serpent'],
    ['cried', 'the', 'pigeon'],
    ['im', 'not', 'a', 'serpent'],
    ['said', 'alice', 'indignantly'],
    ['let', 'me', 'alone'],
    ['ive', 'tried', 'the', 'roots', 'of', 'trees', 'and', 'ive', 'tried',
     'banks', 'and', 'ive', 'tried', 'hedges', 'the', 'pigeon', 'went',
     'on', 'but', 'those', 'serpents'],
    ['theres', 'no', 'pleasing', 'them'],
    ['alice', 'was', 'more', 'and', 'more', 'puzzled'],
    ['as', 'if', 'it', 'wasnt', 'trouble', 'enough', 'hatching', 'the',
     'eggs', 'said', 'the', 'pigeon', 'but', 'i', 'must', 'be', 'on', 'the',
     'lookout', 'for', 'serpents', 'night', 'and', 'day'],
    ['and', 'just', 'as', 'id', 'taken', 'the', 'highest', 'tree', 'in',
     'the', 'wood', 'continued', 'the', 'pigeon', 'raising', 'its', 'voice',
     'to', 'a', 'shriek', 'and', 'just', 'as', 'i', 'was', 'thinking', 'i',
     'should', 'be', 'free', 'of', 'them', 'at', 'last', 'they', 'must',
     'needs', 'come', 'wriggling', 'down', 'from', 'the', 'sky'],
    ['ugh', 'serpent'],
    ['but', 'im', 'not', 'a', 'serpent', 'i', 'tell', 'you'],
    ['said', 'alice'],
    ['im', 'aim', 'aim', 'a', 'little', 'girl', 'she', 'added', 'rather',
     'doubtfully', 'as', 'she', 'remembered', 'the', 'number', 'of',
     'changes', 'she', 'had', 'gone', 'through', 'that', 'day'],
    ['youre', 'looking', 'for', 'eggs', 'i', 'know', 'that', 'well',
     'enough', 'said', 'the', 'pigeon;', 'and', 'what', 'does', 'it',
     'matter', 'to', 'me', 'whether', 'youre', 'a', 'little', 'girl', 'or',
     'a', 'serpent'],
    ['it', 'matters', 'a', 'good', 'deal', 'to', 'me', 'said', 'alice',
     'hastily;', 'but', 'im', 'not', 'looking', 'for', 'eggs', 'as', 'it',
     'happens', 'and', 'if', 'i', 'was', 'i', 'shouldnt', 'want', 'yoursi',
     'dont', 'like', 'them', 'raw'],
    ['well', 'be', 'off', 'then'],
    ['said', 'the', 'pigeon', 'in', 'a', 'sulky', 'tone', 'as', 'it',
     'settled', 'down', 'again', 'into', 'its', 'nest'],
    ['alice', 'crouched', 'down', 'among', 'the', 'trees', 'as', 'well',
     'as', 'she', 'could', 'for', 'her', 'neck', 'kept', 'getting',
     'entangled', 'among', 'the', 'branches', 'and', 'every', 'now', 'and',
     'then', 'she', 'had', 'to', 'stop', 'and', 'untwist', 'it'],
    ['after', 'awhile', 'she', 'remembered', 'that', 'she', 'still', 'held',
     'the', 'pieces', 'of', 'mushroom', 'in', 'her', 'hands', 'and', 'she',
     'set', 'to', 'work', 'very', 'carefully', 'nibbling', 'first', 'at',
     'one', 'and', 'then', 'at', 'the', 'other', 'and', 'growing',
     'sometimes', 'taller', 'and', 'sometimes', 'shorter', 'until', 'she',
     'had', 'succeeded', 'in', 'bringing', 'herself', 'down', 'to', 'her',
     'usual', 'height'],
    ['it', 'was', 'so', 'long', 'since', 'she', 'had', 'been', 'anything',
     'near', 'the', 'right', 'size', 'that', 'it', 'felt', 'quite',
     'strange', 'at', 'first'],
    ['the', 'next', 'thing', 'is', 'to', 'get', 'into', 'that', 'beautiful',
     'gardenhow', 'is', 'that', 'to', 'be', 'done', 'i', 'wonder'],
    ['as', 'she', 'said', 'this', 'she', 'came', 'suddenly', 'upon', 'an',
     'open', 'place', 'with', 'a', 'little', 'house', 'in', 'it', 'about',
     'four', 'feet', 'high'],
    ['whoever', 'lives', 'there', 'thought', 'alice', 'itll', 'never', 'do',
     'to', 'come', 'upon', 'them', 'this', 'size;', 'why', 'i', 'should',
     'frighten', 'them', 'out', 'of', 'their', 'wits'],
    ['she', 'did', 'not', 'venture', 'to', 'go', 'near', 'the', 'house',
     'till', 'she', 'had', 'brought', 'herself', 'down', 'to', 'nine',
     'inches', 'high'],
    ['', 'vipig', 'and', 'pepper', 'for', 'a', 'minute', 'or', 'two', 'she',
     'stood', 'looking', 'at', 'the', 'house', 'when', 'suddenly', 'a',
     'footman', 'in', 'livery', 'came', 'running', 'out', 'of', 'the',
     'wood', '(judging', 'by', 'his', 'face', 'only', 'she', 'would',
     'have', 'called', 'him', 'a', 'fish)and', 'rapped', 'loudly', 'at',
     'the', 'door', 'with', 'his', 'knuckles'],
    ['it', 'was', 'opened', 'by', 'another', 'footman', 'in', 'livery',
     'with', 'a', 'round', 'face', 'and', 'large', 'eyes', 'like', 'a',
     'frog'],
    ['', 'the', 'fishfootman', 'began', 'by', 'producing', 'from', 'under',
     'his', 'arm', 'a', 'great', 'letter', 'and', 'this', 'he', 'handed',
     'over', 'to', 'the', 'other', 'saying', 'in', 'a', 'solemn', 'tone',
     'for', 'the', 'duchess'],
    ['an', 'invitation', 'from', 'the', 'queen', 'to', 'play', 'croquet'],
    ['the', 'frogfootman', 'repeated', 'in', 'the', 'same', 'solemn',
     'tone', 'from', 'the', 'queen'],
    ['an', 'invitation', 'for', 'the', 'duchess', 'to', 'play', 'croquet'],
    ['then', 'they', 'both', 'bowed', 'low', 'and', 'their', 'curls', 'got',
     'entangled', 'together'],
    ['when', 'alice', 'next', 'peeped', 'out', 'the', 'fishfootman', 'was',
     'gone', 'and', 'the', 'other', 'was', 'sitting', 'on', 'the', 'ground',
     'near', 'the', 'door', 'staring', 'stupidly', 'up', 'into', 'the',
     'sky'],
    ['alice', 'went', 'timidly', 'up', 'to', 'the', 'door', 'and',
     'knocked'],
    ['theres', 'no', 'sort', 'of', 'use', 'in', 'knocking', 'said', 'the',
     'footman', 'and', 'that', 'for', 'two', 'reasons'],
    ['first', 'because', 'im', 'on', 'the', 'same', 'side', 'of', 'the',
     'door', 'as', 'you', 'are;', 'secondly', 'because', 'theyre', 'making',
     'such', 'a', 'noise', 'inside', 'no', 'one', 'could', 'possibly',
     'hear', 'you'],
    ['and', 'certainly', 'there', 'was', 'a', 'most', 'extraordinary',
     'noise', 'going', 'on', 'withina', 'constant', 'howling', 'and',
     'sneezing', 'and', 'every', 'now', 'and', 'then', 'a', 'great',
     'crash', 'as', 'if', 'a', 'dish', 'or', 'kettle', 'had', 'been',
     'broken', 'to', 'pieces'],
    ['how', 'am', 'i', 'to', 'get', 'in'],
    ['asked', 'alice'],
    ['are', 'you', 'to', 'get', 'in', 'at', 'all'],
    ['said', 'the', 'footman'],
    ['thats', 'the', 'first', 'question', 'you', 'know'],
    ['alice', 'opened', 'the', 'door', 'and', 'went', 'in'],
    ['the', 'door', 'led', 'right', 'into', 'a', 'large', 'kitchen',
     'which', 'was', 'full', 'of', 'smoke', 'from', 'one', 'end', 'to',
     'the', 'other;', 'the', 'duchess', 'was', 'sitting', 'on', 'a',
     'threelegged', 'stool', 'in', 'the', 'middle', 'nursing', 'a', 'baby;',
     'the', 'cook', 'was', 'leaning', 'over', 'the', 'fire', 'stirring',
     'a', 'large', 'caldron', 'which', 'seemed', 'to', 'be', 'full', 'of',
     'soup'],
    ['theres', 'certainly', 'too', 'much', 'pepper', 'in', 'that', 'soup'],
    ['alice', 'said', 'to', 'herself', 'as', 'well', 'as', 'she', 'could',
     'for', 'sneezing'],
    ['even', 'the', 'duchess', 'sneezed', 'occasionally;', 'and', 'as',
     'for', 'the', 'baby', 'it', 'was', 'sneezing', 'and', 'howling',
     'alternately', 'without', 'a', 'moments', 'pause'],
    ['the', 'only', 'two', 'creatures', 'in', 'the', 'kitchen', 'that',
     'did', 'not', 'sneeze', 'were', 'the', 'cook', 'and', 'a', 'large',
     'cat', 'which', 'was', 'grinning', 'from', 'ear', 'to', 'ear'],
    ['please', 'would', 'you', 'tell', 'me', 'said', 'alice', 'a', 'little',
     'timidly', 'why', 'your', 'cat', 'grins', 'like', 'that'],
    ['its', 'a', 'cheshirecat', 'said', 'the', 'duchess', 'and', 'thats',
     'why'],
    ['i', 'didnt', 'know', 'that', 'cheshirecats', 'always', 'grinned;',
     'in', 'fact', 'i', 'didnt', 'know', 'that', 'cats', 'could', 'grin',
     'said', 'alice'],
    ['you', 'dont', 'know', 'much', 'said', 'the', 'duchess', 'and',
     'thats', 'a', 'fact'],
    ['just', 'then', 'the', 'cook', 'took', 'the', 'caldron', 'of', 'soup',
     'off', 'the', 'fire', 'and', 'at', 'once', 'set', 'to', 'work',
     'throwing', 'everything', 'within', 'her', 'reach', 'at', 'the',
     'duchess', 'and', 'the', 'babythe', 'fireirons', 'came', 'first;',
     'then', 'followed', 'a', 'shower', 'of', 'saucepans', 'plates', 'and',
     'dishes'],
    ['the', 'duchess', 'took', 'no', 'notice', 'of', 'them', 'even', 'when',
     'they', 'hit', 'her', 'and', 'the', 'baby', 'was', 'howling', 'so',
     'much', 'already', 'that', 'it', 'was', 'quite', 'impossible', 'to',
     'say', 'whether', 'the', 'blows', 'hurt', 'it', 'or', 'not'],
    ['oh', 'please', 'mind', 'what', 'youre', 'doing'],
    ['cried', 'alice', 'jumping', 'up', 'and', 'down', 'in', 'an', 'agony',
     'of', 'terror'],
    ['here'],
    ['you', 'may', 'nurse', 'it', 'a', 'bit', 'if', 'you', 'like'],
    ['the', 'duchess', 'said', 'to', 'alice', 'flinging', 'the', 'baby',
     'at', 'her', 'as', 'she', 'spoke'],
    ['i', 'must', 'go', 'and', 'get', 'ready', 'to', 'play', 'croquet',
     'with', 'the', 'queen', 'and', 'she', 'hurried', 'out', 'of', 'the',
     'room'],
    ['alice', 'caught', 'the', 'baby', 'with', 'some', 'difficulty', 'as',
     'it', 'was', 'a', 'queershaped', 'little', 'creature', 'and', 'held',
     'out', 'its', 'arms', 'and', 'legs', 'in', 'all', 'directions'],
    ['if', 'i', 'dont', 'take', 'this', 'child', 'away', 'with', 'me',
     'thought', 'alice', 'theyre', 'sure', 'to', 'kill', 'it', 'in', 'a',
     'day', 'or', 'two'],
    ['wouldnt', 'it', 'be', 'murder', 'to', 'leave', 'it', 'behind'],
    ['she', 'said', 'the', 'last', 'words', 'out', 'loud', 'and', 'the',
     'little', 'thing', 'grunted', 'in', 'reply'],
    ['if', 'youre', 'going', 'to', 'turn', 'into', 'a', 'pig', 'my', 'dear',
     'said', 'alice', 'ill', 'have', 'nothing', 'more', 'to', 'do', 'with',
     'you'],
    ['mind', 'now'],
    ['alice', 'was', 'just', 'beginning', 'to', 'think', 'to', 'herself',
     'now', 'what', 'am', 'i', 'to', 'do', 'with', 'this', 'creature',
     'when', 'i', 'get', 'it', 'home'],
    ['when', 'it', 'grunted', 'again', 'so', 'violently', 'that', 'alice',
     'looked', 'down', 'into', 'its', 'face', 'in', 'some', 'alarm'],
    ['this', 'time', 'there', 'could', 'be', 'no', 'mistake', 'about',
     'itit', 'was', 'neither', 'more', 'nor', 'less', 'than', 'a', 'pig;',
     'so', 'she', 'set', 'the', 'little', 'creature', 'down', 'and', 'felt',
     'quite', 'relieved', 'to', 'see', 'it', 'trot', 'away', 'quietly',
     'into', 'the', 'wood'],
    ['alice', 'was', 'a', 'little', 'startled', 'by', 'seeing', 'the',
     'cheshirecat', 'sitting', 'on', 'a', 'bough', 'of', 'a', 'tree', 'a',
     'few', 'yards', 'off'],
    ['the', 'cat', 'only', 'grinned', 'when', 'it', 'saw', 'her'],
    ['cheshirepuss', 'began', 'alice', 'rather', 'timidly', 'would', 'you',
     'please', 'tell', 'me', 'which', 'way', 'i', 'ought', 'to', 'go',
     'from', 'here'],
    ['in', 'that', 'direction', 'the', 'cat', 'said', 'waving', 'the',
     'right', 'paw', 'round', 'lives', 'a', 'hatter;', 'and', 'in', 'that',
     'direction', 'waving', 'the', 'other', 'paw', 'lives', 'a', 'march',
     'hare'],
    ['visit', 'either', 'you', 'like;', 'theyre', 'both', 'mad'],
    ['but', 'i', 'dont', 'want', 'to', 'go', 'among', 'mad', 'people',
     'alice', 'remarked'],
    ['oh', 'you', 'cant', 'help', 'that', 'said', 'the', 'cat;', 'were',
     'all', 'mad', 'here'],
    ['do', 'you', 'play', 'croquet', 'with', 'the', 'queen', 'today'],
    ['i', 'should', 'like', 'it', 'very', 'much', 'said', 'alice', 'but',
     'i', 'havent', 'been', 'invited', 'yet'],
    ['youll', 'see', 'me', 'there', 'said', 'the', 'cat', 'and',
     'vanished'],
    ['alice', 'had', 'not', 'gone', 'much', 'farther', 'before', 'she',
     'came', 'in', 'sight', 'of', 'the', 'house', 'of', 'the', 'march',
     'hare;', 'it', 'was', 'so', 'large', 'a', 'house', 'that', 'she',
     'did', 'not', 'like', 'to', 'go', 'near', 'till', 'she', 'had',
     'nibbled', 'some', 'more', 'of', 'the', 'lefthand', 'bit', 'of',
     'mushroom'],
    ['', 'viia', 'mad', 'teaparty', 'there', 'was', 'a', 'table', 'set',
     'out', 'under', 'a', 'tree', 'in', 'front', 'of', 'the', 'house',
     'and', 'the', 'march', 'hare', 'and', 'the', 'hatter', 'were',
     'having', 'tea', 'at', 'it;', 'a', 'dormouse', 'was', 'sitting',
     'between', 'them', 'fast', 'asleep'],
    ['the', 'table', 'was', 'a', 'large', 'one', 'but', 'the', 'three',
     'were', 'all', 'crowded', 'together', 'at', 'one', 'corner', 'of',
     'it'],
    ['no', 'room'],
    ['no', 'room'],
    ['they', 'cried', 'out', 'when', 'they', 'saw', 'alice', 'coming'],
    ['theres', 'plenty', 'of', 'room'],
    ['said', 'alice', 'indignantly', 'and', 'she', 'sat', 'down', 'in', 'a',
     'large', 'armchair', 'at', 'one', 'end', 'of', 'the', 'table'],
    ['the', 'hatter', 'opened', 'his', 'eyes', 'very', 'wide', 'on',
     'hearing', 'this', 'but', 'all', 'he', 'said', 'was', 'why', 'is', 'a',
     'raven', 'like', 'a', 'writingdesk'],
    ['im', 'glad', 'theyve', 'begun', 'asking', 'riddlesi', 'believe', 'i',
     'can', 'guess', 'that', 'she', 'added', 'aloud'],
    ['do', 'you', 'mean', 'that', 'you', 'think', 'you', 'can', 'find',
     'out', 'the', 'answer', 'to', 'it'],
    ['said', 'the', 'march', 'hare'],
    ['exactly', 'so', 'said', 'alice'],
    ['then', 'you', 'should', 'say', 'what', 'you', 'mean', 'the', 'march',
     'hare', 'went', 'on'],
    ['i', 'do', 'alice', 'hastily', 'replied;', 'at', 'leastat', 'least',
     'i', 'mean', 'what', 'i', 'saythats', 'the', 'same', 'thing', 'you',
     'know'],
    ['you', 'might', 'just', 'as', 'well', 'say', 'added', 'the',
     'dormouse', 'which', 'seemed', 'to', 'be', 'talking', 'in', 'its',
     'sleep', 'that', 'i', 'breathe', 'when', 'i', 'sleep', 'is', 'the',
     'same', 'thing', 'as', 'i', 'sleep', 'when', 'i', 'breathe'],
    ['it', 'is', 'the', 'same', 'thing', 'with', 'you', 'said', 'the',
     'hatter', 'and', 'he', 'poured', 'a', 'little', 'hot', 'tea', 'upon',
     'its', 'nose'],
    ['the', 'dormouse', 'shook', 'its', 'head', 'impatiently', 'and',
     'said', 'without', 'opening', 'its', 'eyes', 'of', 'course', 'of',
     'course;', 'just', 'what', 'i', 'was', 'going', 'to', 'remark',
     'myself'],
    ['', 'have', 'you', 'guessed', 'the', 'riddle', 'yet'],
    ['the', 'hatter', 'said', 'turning', 'to', 'alice', 'again'],
    ['no', 'i', 'give', 'it', 'up', 'alice', 'replied'],
    ['whats', 'the', 'answer'],
    ['i', 'havent', 'the', 'slightest', 'idea', 'said', 'the', 'hatter'],
    ['nor', 'i', 'said', 'the', 'march', 'hare'],
    ['alice', 'gave', 'a', 'weary', 'sigh'],
    ['i', 'think', 'you', 'might', 'do', 'something', 'better', 'with',
     'the', 'time', 'she', 'said', 'than', 'wasting', 'it', 'in', 'asking',
     'riddles', 'that', 'have', 'no', 'answers'],
    ['take', 'some', 'more', 'tea', 'the', 'march', 'hare', 'said', 'to',
     'alice', 'very', 'earnestly'],
    ['ive', 'had', 'nothing', 'yet', 'alice', 'replied', 'in', 'an',
     'offended', 'tone', 'so', 'i', 'cant', 'take', 'more'],
    ['you', 'mean', 'you', 'cant', 'take', 'less', 'said', 'the', 'hatter;',
     'its', 'very', 'easy', 'to', 'take', 'more', 'than', 'nothing'],
    ['at', 'this', 'alice', 'got', 'up', 'and', 'walked', 'off'],
    ['the', 'dormouse', 'fell', 'asleep', 'instantly', 'and', 'neither',
     'of', 'the', 'others', 'took', 'the', 'least', 'notice', 'of', 'her',
     'going', 'though', 'she', 'looked', 'back', 'once', 'or', 'twice;',
     'the', 'last', 'time', 'she', 'saw', 'them', 'they', 'were', 'trying',
     'to', 'put', 'the', 'dormouse', 'into', 'the', 'teapot'],
    ['', 'at', 'any', 'rate', 'ill', 'never', 'go', 'there', 'again'],
    ['said', 'alice', 'as', 'she', 'picked', 'her', 'way', 'through', 'the',
     'wood'],
    ['its', 'the', 'stupidest', 'teaparty', 'i', 'ever', 'was', 'at', 'in',
     'all', 'my', 'life'],
    ['just', 'as', 'she', 'said', 'this', 'she', 'noticed', 'that', 'one',
     'of', 'the', 'trees', 'had', 'a', 'door', 'leading', 'right', 'into',
     'it'],
    ['thats', 'very', 'curious'],
    ['she', 'thought'],
    ['i', 'think', 'i', 'may', 'as', 'well', 'go', 'in', 'at', 'once'],
    ['and', 'in', 'she', 'went'],
    ['once', 'more', 'she', 'found', 'herself', 'in', 'the', 'long', 'hall',
     'and', 'close', 'to', 'the', 'little', 'glass', 'table'],
    ['taking', 'the', 'little', 'golden', 'key', 'she', 'unlocked', 'the',
     'door', 'that', 'led', 'into', 'the', 'garden'],
    ['then', 'she', 'set', 'to', 'work', 'nibbling', 'at', 'the',
     'mushroom', '(she', 'had', 'kept', 'a', 'piece', 'of', 'it', 'in',
     'her', 'pocket)', 'till', 'she', 'was', 'about', 'a', 'foot', 'high;',
     'then', 'she', 'walked', 'down', 'the', 'little', 'passage;', 'and',
     'thenshe', 'found', 'herself', 'at', 'last', 'in', 'the', 'beautiful',
     'garden', 'among', 'the', 'bright', 'flowerbeds', 'and', 'the', 'cool',
     'fountains'],
    ['', 'viiithe', 'queens', 'croquet', 'ground', 'a', 'large', 'rosetree',
     'stood', 'near', 'the', 'entrance', 'of', 'the', 'garden;', 'the',
     'roses', 'growing', 'on', 'it', 'were', 'white', 'but', 'there',
     'were', 'three', 'gardeners', 'at', 'it', 'busily', 'painting', 'them',
     'red'],
    ['suddenly', 'their', 'eyes', 'chanced', 'to', 'fall', 'upon', 'alice',
     'as', 'she', 'stood', 'watching', 'them'],
    ['would', 'you', 'tell', 'me', 'please', 'said', 'alice', 'a', 'little',
     'timidly', 'why', 'you', 'are', 'painting', 'those', 'roses'],
    ['five', 'and', 'seven', 'said', 'nothing', 'but', 'looked', 'at',
     'two'],
    ['two', 'began', 'in', 'a', 'low', 'voice', 'why', 'the', 'fact', 'is',
     'you', 'see', 'miss', 'this', 'here', 'ought', 'to', 'have', 'been',
     'a', 'red', 'rosetree', 'and', 'we', 'put', 'a', 'white', 'one', 'in',
     'by', 'mistake;', 'and', 'if', 'the', 'queen', 'was', 'to', 'find',
     'it', 'out', 'we', 'should', 'all', 'have', 'our', 'heads', 'cut',
     'off', 'you', 'know'],
    ['so', 'you', 'see', 'miss', 'were', 'doing', 'our', 'best', 'afore',
     'she', 'comes', 'to', 'at', 'this', 'moment', 'five', 'who', 'had',
     'been', 'anxiously', 'looking', 'across', 'the', 'garden', 'called',
     'out', 'the', 'queen'],
    ['the', 'queen'],
    ['and', 'the', 'three', 'gardeners', 'instantly', 'threw', 'themselves',
     'flat', 'upon', 'their', 'faces'],
    ['there', 'was', 'a', 'sound', 'of', 'many', 'footsteps', 'and',
     'alice', 'looked', 'round', 'eager', 'to', 'see', 'the', 'queen'],
    ['first', 'came', 'ten', 'soldiers', 'carrying', 'clubs', 'with',
     'their', 'hands', 'and', 'feet', 'at', 'the', 'corners:', 'next',
     'the', 'ten', 'courtiers;', 'these', 'were', 'ornamented', 'all',
     'over', 'with', 'diamonds'],
    ['after', 'these', 'came', 'the', 'royal', 'children;', 'there', 'were',
     'ten', 'of', 'them', 'all', 'ornamented', 'with', 'hearts'],
    ['next', 'came', 'the', 'guests', 'mostly', 'kings', 'and', 'queens',
     'and', 'among', 'them', 'alice', 'recognized', 'the', 'white',
     'rabbit'],
    ['then', 'followed', 'the', 'knave', 'of', 'hearts', 'carrying', 'the',
     'kings', 'crown', 'on', 'a', 'crimson', 'velvet', 'cushion;', 'and',
     'last', 'of', 'all', 'this', 'grand', 'procession', 'came', 'the',
     'king', 'and', 'the', 'queen', 'of', 'hearts'],
    ['when', 'the', 'procession', 'came', 'opposite', 'to', 'alice', 'they',
     'all', 'stopped', 'and', 'looked', 'at', 'her', 'and', 'the', 'queen',
     'said', 'severely', 'who', 'is', 'this'],
    ['she', 'said', 'it', 'to', 'the', 'knave', 'of', 'hearts', 'who',
     'only', 'bowed', 'and', 'smiled', 'in', 'reply'],
    ['my', 'name', 'is', 'alice', 'so', 'please', 'your', 'majesty', 'said',
     'alice', 'very', 'politely;', 'but', 'she', 'added', 'to', 'herself',
     'why', 'theyre', 'only', 'a', 'pack', 'of', 'cards', 'after', 'all'],
    ['can', 'you', 'play', 'croquet'],
    ['shouted', 'the', 'queen'],
    ['the', 'question', 'was', 'evidently', 'meant', 'for', 'alice'],
    ['yes'],
    ['said', 'alice', 'loudly'],
    ['come', 'on', 'then'],
    ['roared', 'the', 'queen'],
    ['itsits', 'a', 'very', 'fine', 'day'],
    ['said', 'a', 'timid', 'voice', 'to', 'alice'],
    ['she', 'was', 'walking', 'by', 'the', 'white', 'rabbit', 'who', 'was',
     'peeping', 'anxiously', 'into', 'her', 'face'],
    ['very', 'said', 'alice'],
    ['wheres', 'the', 'duchess'],
    ['hush'],
    ['hush'],
    ['said', 'the', 'rabbit'],
    ['shes', 'under', 'sentence', 'of', 'execution'],
    ['what', 'for'],
    ['said', 'alice'],
    ['she', 'boxed', 'the', 'queens', 'ears', 'the', 'rabbit', 'began'],
    ['get', 'to', 'your', 'places'],
    ['shouted', 'the', 'queen', 'in', 'a', 'voice', 'of', 'thunder', 'and',
     'people', 'began', 'running', 'about', 'in', 'all', 'directions',
     'tumbling', 'up', 'against', 'each', 'other'],
    ['however', 'they', 'got', 'settled', 'down', 'in', 'a', 'minute', 'or',
     'two', 'and', 'the', 'game', 'began'],
    ['alice', 'thought', 'she', 'had', 'never', 'seen', 'such', 'a',
     'curious', 'croquetground', 'in', 'her', 'life;', 'it', 'was', 'all',
     'ridges', 'and', 'furrows'],
    ['the', 'croquet', 'balls', 'were', 'live', 'hedgehogs', 'and', 'the',
     'mallets', 'live', 'flamingos', 'and', 'the', 'soldiers', 'had', 'to',
     'double', 'themselves', 'up', 'and', 'stand', 'on', 'their', 'hands',
     'and', 'feet', 'to', 'make', 'the', 'arches'],
    ['the', 'players', 'all', 'played', 'at', 'once', 'without', 'waiting',
     'for', 'turns', 'quarrelling', 'all', 'the', 'while', 'and',
     'fighting', 'for', 'the', 'hedgehogs;', 'and', 'in', 'a', 'very',
     'short', 'time', 'the', 'queen', 'was', 'in', 'a', 'furious',
     'passion', 'and', 'went', 'stamping', 'about', 'and', 'shouting',
     'off', 'with', 'his', 'head'],
    ['or', 'off', 'with', 'her', 'head'],
    ['about', 'once', 'in', 'a', 'minute'],
    ['theyre', 'dreadfully', 'fond', 'of', 'beheading', 'people', 'here',
     'thought', 'alice;', 'the', 'great', 'wonder', 'is', 'that', 'theres',
     'anyone', 'left', 'alive'],
    ['she', 'was', 'looking', 'about', 'for', 'some', 'way', 'of', 'escape',
     'when', 'she', 'noticed', 'a', 'curious', 'appearance', 'in', 'the',
     'air'],
    ['its', 'the', 'cheshirecat', 'she', 'said', 'to', 'herself;', 'now',
     'i', 'shall', 'have', 'somebody', 'to', 'talk', 'to'],
    ['how', 'are', 'you', 'getting', 'on'],
    ['said', 'the', 'cat'],
    ['i', 'dont', 'think', 'they', 'play', 'at', 'all', 'fairly', 'alice',
     'said', 'in', 'a', 'rather', 'complaining', 'tone;', 'and', 'they',
     'all', 'quarrel', 'so', 'dreadfully', 'one', 'cant', 'hear', 'oneself',
     'speakand', 'they', 'dont', 'seem', 'to', 'have', 'any', 'rules', 'in',
     'particular'],
    ['how', 'do', 'you', 'like', 'the', 'queen'],
    ['said', 'the', 'cat', 'in', 'a', 'low', 'voice'],
    ['not', 'at', 'all', 'said', 'alice'],
    ['', 'alice', 'thought', 'she', 'might', 'as', 'well', 'go', 'back',
     'and', 'see', 'how', 'the', 'game', 'was', 'going', 'on'],
    ['so', 'she', 'went', 'off', 'in', 'search', 'of', 'her', 'hedgehog'],
    ['the', 'hedgehog', 'was', 'engaged', 'in', 'a', 'fight', 'with',
     'another', 'hedgehog', 'which', 'seemed', 'to', 'alice', 'an',
     'excellent', 'opportunity', 'for', 'croqueting', 'one', 'of', 'them',
     'with', 'the', 'other;', 'the', 'only', 'difficulty', 'was', 'that',
     'her', 'flamingo', 'was', 'gone', 'across', 'to', 'the', 'other',
     'side', 'of', 'the', 'garden', 'where', 'alice', 'could', 'see', 'it',
     'trying', 'in', 'a', 'helpless', 'sort', 'of', 'way', 'to', 'fly',
     'up', 'into', 'a', 'tree'],
    ['she', 'caught', 'the', 'flamingo', 'and', 'tucked', 'it', 'away',
     'under', 'her', 'arm', 'that', 'it', 'might', 'not', 'escape',
     'again'],
    ['just', 'then', 'alice', 'ran', 'across', 'the', 'duchess', '(who',
     'was', 'now', 'out', 'of', 'prison)'],
    ['she', 'tucked', 'her', 'arm', 'affectionately', 'into', 'alices',
     'and', 'they', 'walked', 'off', 'together'],
    ['alice', 'was', 'very', 'glad', 'to', 'find', 'her', 'in', 'such', 'a',
     'pleasant', 'temper'],
    ['she', 'was', 'a', 'little', 'startled', 'however', 'when', 'she',
     'heard', 'the', 'voice', 'of', 'the', 'duchess', 'close', 'to', 'her',
     'ear'],
    ['youre', 'thinking', 'about', 'something', 'my', 'dear', 'and', 'that',
     'makes', 'you', 'forget', 'to', 'talk'],
    ['the', 'games', 'going', 'on', 'rather', 'better', 'now', 'alice',
     'said', 'by', 'way', 'of', 'keeping', 'up', 'the', 'conversation', 'a',
     'little'],
    ['tis', 'so', 'said', 'the', 'duchess;', 'and', 'the', 'moral', 'of',
     'that', 'isoh', 'tis', 'love', 'tis', 'love', 'that', 'makes', 'the',
     'world', 'go', 'round'],
    ['somebody', 'said', 'alice', 'whispered', 'that', 'its', 'done', 'by',
     'everybody', 'minding', 'his', 'own', 'business'],
    ['ah', 'well'],
    ['it', 'means', 'much', 'the', 'same', 'thing', 'said', 'the',
     'duchess', 'digging', 'her', 'sharp', 'little', 'chin', 'into',
     'alices', 'shoulder', 'as', 'she', 'added', 'and', 'the', 'moral',
     'of', 'that', 'istake', 'care', 'of', 'the', 'sense', 'and', 'the',
     'sounds', 'will', 'take', 'care', 'of', 'themselves'],
    ['to', 'alices', 'great', 'surprise', 'the', 'duchesss', 'arm', 'that',
     'was', 'linked', 'into', 'hers', 'began', 'to', 'tremble'],
    ['alice', 'looked', 'up', 'and', 'there', 'stood', 'the', 'queen', 'in',
     'front', 'of', 'them', 'with', 'her', 'arms', 'folded', 'frowning',
     'like', 'a', 'thunderstorm'],
    ['now', 'i', 'give', 'you', 'fair', 'warning', 'shouted', 'the',
     'queen', 'stamping', 'on', 'the', 'ground', 'as', 'she', 'spoke',
     'either', 'you', 'or', 'your', 'head', 'must', 'be', 'off', 'and',
     'that', 'in', 'about', 'half', 'no', 'time'],
    ['take', 'your', 'choice'],
    ['the', 'duchess', 'took', 'her', 'choice', 'and', 'was', 'gone', 'in',
     'a', 'moment'],
    ['lets', 'go', 'on', 'with', 'the', 'game', 'the', 'queen', 'said',
     'to', 'alice;', 'and', 'alice', 'was', 'too', 'much', 'frightened',
     'to', 'say', 'a', 'word', 'but', 'slowly', 'followed', 'her', 'back',
     'to', 'the', 'croquetground'],
    ['all', 'the', 'time', 'they', 'were', 'playing', 'the', 'queen',
     'never', 'left', 'off', 'quarreling', 'with', 'the', 'other',
     'players', 'and', 'shouting', 'off', 'with', 'his', 'head'],
    ['or', 'off', 'with', 'her', 'head'],
    ['by', 'the', 'end', 'of', 'half', 'an', 'hour', 'or', 'so', 'all',
     'the', 'players', 'except', 'the', 'king', 'the', 'queen', 'and',
     'alice', 'were', 'in', 'custody', 'of', 'the', 'soldiers', 'and',
     'under', 'sentence', 'of', 'execution'],
    ['then', 'the', 'queen', 'left', 'off', 'quite', 'out', 'of', 'breath',
     'and', 'walked', 'away', 'with', 'alice'],
    ['alice', 'heard', 'the', 'king', 'say', 'in', 'a', 'low', 'voice',
     'to', 'the', 'company', 'generally', 'you', 'are', 'all', 'pardoned'],
    ['suddenly', 'the', 'cry', 'the', 'trials', 'beginning'],
    ['was', 'heard', 'in', 'the', 'distance', 'and', 'alice', 'ran',
     'along', 'with', 'the', 'others'],
    ['', 'ixwho', 'stole', 'the', 'tarts'],
    ['the', 'king', 'and', 'queen', 'of', 'hearts', 'were', 'seated', 'on',
     'their', 'throne', 'when', 'they', 'arrived', 'with', 'a', 'great',
     'crowd', 'assembled', 'about', 'themall', 'sorts', 'of', 'little',
     'birds', 'and', 'beasts', 'as', 'well', 'as', 'the', 'whole', 'pack',
     'of', 'cards:', 'the', 'knave', 'was', 'standing', 'before', 'them',
     'in', 'chains', 'with', 'a', 'soldier', 'on', 'each', 'side', 'to',
     'guard', 'him;', 'and', 'near', 'the', 'king', 'was', 'the', 'white',
     'rabbit', 'with', 'a', 'trumpet', 'in', 'one', 'hand', 'and', 'a',
     'scroll', 'of', 'parchment', 'in', 'the', 'other'],
    ['in', 'the', 'very', 'middle', 'of', 'the', 'court', 'was', 'a',
     'table', 'with', 'a', 'large', 'dish', 'of', 'tarts', 'upon', 'it'],
    ['i', 'wish', 'theyd', 'get', 'the', 'trial', 'done', 'alice',
     'thought', 'and', 'hand', 'round', 'the', 'refreshments'],
    ['the', 'judge', 'by', 'the', 'way', 'was', 'the', 'king', 'and', 'he',
     'wore', 'his', 'crown', 'over', 'his', 'great', 'wig'],
    ['thats', 'the', 'jurybox', 'thought', 'alice;', 'and', 'those',
     'twelve', 'creatures', '(some', 'were', 'animals', 'and', 'some',
     'were', 'birds)', 'i', 'suppose', 'they', 'are', 'the', 'jurors'],
    ['just', 'then', 'the', 'white', 'rabbit', 'cried', 'out', 'silence',
     'in', 'the', 'court'],
    ['herald', 'read', 'the', 'accusation'],
    ['said', 'the', 'king'],
    ['', 'on', 'this', 'the', 'white', 'rabbit', 'blew', 'three', 'blasts',
     'on', 'the', 'trumpet', 'then', 'unrolled', 'the', 'parchmentscroll',
     'and', 'read', 'as', 'follows:', 'the', 'queen', 'of', 'hearts', 'she',
     'made', 'some', 'tarts', 'all', 'on', 'a', 'summer', 'day;', 'the',
     'knave', 'of', 'hearts', 'he', 'stole', 'those', 'tarts', 'and',
     'took', 'them', 'quite', 'away'],
    ['call', 'the', 'first', 'witness', 'said', 'the', 'king;', 'and',
     'the', 'white', 'rabbit', 'blew', 'three', 'blasts', 'on', 'the',
     'trumpet', 'and', 'called', 'out', 'first', 'witness'],
    ['the', 'first', 'witness', 'was', 'the', 'hatter'],
    ['he', 'came', 'in', 'with', 'a', 'teacup', 'in', 'one', 'hand', 'and',
     'a', 'piece', 'of', 'bread', 'and', 'butter', 'in', 'the', 'other'],
    ['you', 'ought', 'to', 'have', 'finished', 'said', 'the', 'king'],
    ['when', 'did', 'you', 'begin'],
    ['the', 'hatter', 'looked', 'at', 'the', 'march', 'hare', 'who', 'had',
     'followed', 'him', 'into', 'the', 'court', 'arm', 'in', 'arm', 'with',
     'the', 'dormouse'],
    ['fourteenth', 'of', 'march', 'i', 'think', 'it', 'was', 'he', 'said'],
    ['give', 'your', 'evidence', 'said', 'the', 'king', 'and', 'dont', 'be',
     'nervous', 'or', 'ill', 'have', 'you', 'executed', 'on', 'the',
     'spot'],
    ['this', 'did', 'not', 'seem', 'to', 'encourage', 'the', 'witness',
     'at', 'all;', 'he', 'kept', 'shifting', 'from', 'one', 'foot', 'to',
     'the', 'other', 'looking', 'uneasily', 'at', 'the', 'queen', 'and',
     'in', 'his', 'confusion', 'he', 'bit', 'a', 'large', 'piece', 'out',
     'of', 'his', 'teacup', 'instead', 'of', 'the', 'bread', 'and',
     'butter'],
    ['just', 'at', 'this', 'moment', 'alice', 'felt', 'a', 'very',
     'curious', 'sensationshe', 'was', 'beginning', 'to', 'grow', 'larger',
     'again'],
    ['the', 'miserable', 'hatter', 'dropped', 'his', 'teacup', 'and',
     'bread', 'and', 'butter', 'and', 'went', 'down', 'on', 'one', 'knee'],
    ['im', 'a', 'poor', 'man', 'your', 'majesty', 'he', 'began'],
    ['youre', 'a', 'very', 'poor', 'speaker', 'said', 'the', 'king'],
    ['you', 'may', 'go', 'said', 'the', 'king', 'and', 'the', 'hatter',
     'hurriedly', 'left', 'the', 'court'],
    ['call', 'the', 'next', 'witness'],
    ['said', 'the', 'king'],
    ['the', 'next', 'witness', 'was', 'the', 'duchesss', 'cook'],
    ['she', 'carried', 'the', 'pepperbox', 'in', 'her', 'hand', 'and',
     'the', 'people', 'near', 'the', 'door', 'began', 'sneezing', 'all',
     'at', 'once'],
    ['give', 'your', 'evidence', 'said', 'the', 'king'],
    ['shant', 'said', 'the', 'cook'],
    ['the', 'king', 'looked', 'anxiously', 'at', 'the', 'white', 'rabbit',
     'who', 'said', 'in', 'a', 'low', 'voice', 'your', 'majesty', 'must',
     'crossexamine', 'this', 'witness'],
    ['well', 'if', 'i', 'must', 'i', 'must', 'the', 'king', 'said'],
    ['what', 'are', 'tarts', 'made', 'of'],
    ['pepper', 'mostly', 'said', 'the', 'cook'],
    ['for', 'some', 'minutes', 'the', 'whole', 'court', 'was', 'in',
     'confusion', 'and', 'by', 'the', 'time', 'they', 'had', 'settled',
     'down', 'again', 'the', 'cook', 'had', 'disappeared'],
    ['never', 'mind'],
    ['said', 'the', 'king', 'call', 'the', 'next', 'witness'],
    ['alice', 'watched', 'the', 'white', 'rabbit', 'as', 'he', 'fumbled',
     'over', 'the', 'list'],
    ['imagine', 'her', 'surprise', 'when', 'he', 'read', 'out', 'at', 'the',
     'top', 'of', 'his', 'shrill', 'little', 'voice', 'the', 'name',
     'alice'],
    ['', 'xalices', 'evidence', 'here'],
    ['cried', 'alice'],
    ['she', 'jumped', 'up', 'in', 'such', 'a', 'hurry', 'that', 'she',
     'tipped', 'over', 'the', 'jurybox', 'upsetting', 'all', 'the',
     'jurymen', 'on', 'to', 'the', 'heads', 'of', 'the', 'crowd', 'below'],
    ['oh', 'i', 'beg', 'your', 'pardon'],
    ['she', 'exclaimed', 'in', 'a', 'tone', 'of', 'great', 'dismay'],
    ['the', 'trial', 'cannot', 'proceed', 'said', 'the', 'king', 'until',
     'all', 'the', 'jurymen', 'are', 'back', 'in', 'their', 'proper',
     'placesall', 'he', 'repeated', 'with', 'great', 'emphasis', 'looking',
     'hard', 'at', 'alice'],
    ['what', 'do', 'you', 'know', 'about', 'this', 'business'],
    ['the', 'king', 'said', 'to', 'alice'],
    ['nothing', 'whatever', 'said', 'alice'],
    ['the', 'king', 'then', 'read', 'from', 'his', 'book:', 'rule',
     'fortytwo'],
    ['all', 'persons', 'more', 'than', 'a', 'mile', 'high', 'to', 'leave',
     'the', 'court'],
    ['im', 'not', 'a', 'mile', 'high', 'said', 'alice'],
    ['nearly', 'two', 'miles', 'high', 'said', 'the', 'queen'],
    ['', 'well', 'i', 'shant', 'go', 'at', 'any', 'rate', 'said', 'alice'],
    ['the', 'king', 'turned', 'pale', 'and', 'shut', 'his', 'notebook',
     'hastily'],
    ['consider', 'your', 'verdict', 'he', 'said', 'to', 'the', 'jury', 'in',
     'a', 'low', 'trembling', 'voice'],
    ['theres', 'more', 'evidence', 'to', 'come', 'yet', 'please', 'your',
     'majesty', 'said', 'the', 'white', 'rabbit', 'jumping', 'up', 'in',
     'a', 'great', 'hurry'],
    ['this', 'paper', 'has', 'just', 'been', 'picked', 'up'],
    ['it', 'seems', 'to', 'be', 'a', 'letter', 'written', 'by', 'the',
     'prisoner', 'toto', 'somebody'],
    ['he', 'unfolded', 'the', 'paper', 'as', 'he', 'spoke', 'and', 'added',
     'it', 'isnt', 'a', 'letter', 'after', 'all;', 'its', 'a', 'set', 'of',
     'verses'],
    ['please', 'your', 'majesty', 'said', 'the', 'knave', 'i', 'didnt',
     'write', 'it', 'and', 'they', 'cant', 'prove', 'that', 'i', 'did;',
     'theres', 'no', 'name', 'signed', 'at', 'the', 'end'],
    ['you', 'must', 'have', 'meant', 'some', 'mischief', 'or', 'else',
     'youd', 'have', 'signed', 'your', 'name', 'like', 'an', 'honest',
     'man', 'said', 'the', 'king'],
    ['there', 'was', 'a', 'general', 'clapping', 'of', 'hands', 'at',
     'this'],
    ['read', 'them', 'he', 'added', 'turning', 'to', 'the', 'white',
     'rabbit'],
    ['there', 'was', 'dead', 'silence', 'in', 'the', 'court', 'whilst',
     'the', 'white', 'rabbit', 'read', 'out', 'the', 'verses'],
    ['thats', 'the', 'most', 'important', 'piece', 'of', 'evidence', 'weve',
     'heard', 'yet', 'said', 'the', 'king'],
    ['i', 'dont', 'believe', 'theres', 'an', 'atom', 'of', 'meaning', 'in',
     'it', 'ventured', 'alice'],
    ['if', 'theres', 'no', 'meaning', 'in', 'it', 'said', 'the', 'king',
     'that', 'saves', 'a', 'world', 'of', 'trouble', 'you', 'know', 'as',
     'we', 'neednt', 'try', 'to', 'find', 'any'],
    ['let', 'the', 'jury', 'consider', 'their', 'verdict'],
    ['no', 'no'],
    ['said', 'the', 'queen'],
    ['sentence', 'firstverdict', 'afterwards'],
    ['stuff', 'and', 'nonsense'],
    ['said', 'alice', 'loudly'],
    ['the', 'idea', 'of', 'having', 'the', 'sentence', 'first'],
    ['hold', 'your', 'tongue'],
    ['said', 'the', 'queen', 'turning', 'purple'],
    ['i', 'wont'],
    ['said', 'alice'],
    ['off', 'with', 'her', 'head'],
    ['the', 'queen', 'shouted', 'at', 'the', 'top', 'of', 'her', 'voice'],
    ['nobody', 'moved'],
    ['who', 'cares', 'for', 'you'],
    ['said', 'alice', '(she', 'had', 'grown', 'to', 'her', 'full', 'size',
     'by', 'this', 'time)'],
    ['youre', 'nothing', 'but', 'a', 'pack', 'of', 'cards'],
    ['at', 'this', 'the', 'whole', 'pack', 'rose', 'up', 'in', 'the', 'air',
     'and', 'came', 'flying', 'down', 'upon', 'her;', 'she', 'gave', 'a',
     'little', 'scream', 'half', 'of', 'fright', 'and', 'half', 'of',
     'anger', 'and', 'tried', 'to', 'beat', 'them', 'off', 'and', 'found',
     'herself', 'lying', 'on', 'the', 'bank', 'with', 'her', 'head', 'in',
     'the', 'lap', 'of', 'her', 'sister', 'who', 'was', 'gently',
     'brushing', 'away', 'some', 'dead', 'leaves', 'that', 'had',
     'fluttered', 'down', 'from', 'the', 'trees', 'upon', 'her', 'face'],
    ['wake', 'up', 'alice', 'dear'],
    ['said', 'her', 'sister'],
    ['why', 'what', 'a', 'long', 'sleep', 'youve', 'had'],
    ['oh', 'ive', 'had', 'such', 'a', 'curious', 'dream'],
    ['said', 'alice'],
    ['and', 'she', 'told', 'her', 'sister', 'as', 'well', 'as', 'she',
     'could', 'remember', 'them', 'all', 'these', 'strange', 'adventures',
     'of', 'hers', 'that', 'you', 'have', 'just', 'been', 'reading',
     'about'],
    ['alice', 'got', 'up', 'and', 'ran', 'off', 'thinking', 'while', 'she',
     'ran', 'as', 'well', 'she', 'might', 'what', 'a', 'wonderful', 'dream',
     'it', 'had', 'been']
]

